const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const path = require('node:path');
const filename = path.resolve('lib/life-domain.ts');
const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const mod = new Module(filename, module); mod._compile(compiled, filename);
const { advanceFocus, plannedSecondsLeft } = mod.exports;
const start = new Date('2026-09-17T12:00:00').getTime();
const plan = { id:'test',name:'Study',focusMinutes:50,breakMinutes:10,sessions:4,completed:0,phase:'focus',running:true,endsAt:start+50*60000,remaining:3000 };
assert.equal(plannedSecondsLeft(plan,start),230*60);
const first = advanceFocus(plan,start+50*60000);
assert.equal(first.plan.phase,'break'); assert.equal(first.plan.completed,1); assert.equal(first.logs.length,1);
assert.equal(plannedSecondsLeft(first.plan,start+50*60000),180*60);
const resumed = advanceFocus(first.plan,start+60*60000);
assert.equal(resumed.plan.phase,'focus'); assert.equal(resumed.logs.length,0);
const done = advanceFocus(plan,start+240*60000);
assert.equal(done.plan.phase,'finished'); assert.equal(done.plan.completed,4); assert.equal(done.logs.length,4);
assert.equal(new Set(done.logs.map(l=>l.id)).size,4); assert.equal(advanceFocus(done.plan,start+300*60000).logs.length,0);
assert.equal(plannedSecondsLeft(done.plan,start+240*60000),0);
const noBreak = advanceFocus({...plan,focusMinutes:1,breakMinutes:0,sessions:2,endsAt:start+60000,remaining:60},start+120000);
assert.equal(noBreak.logs.length,2); assert.equal(noBreak.plan.phase,'finished');
const paused = {...plan,running:false,endsAt:null,remaining:900};
assert.equal(advanceFocus(paused,start+99999999).logs.length,0);
assert.equal(plannedSecondsLeft(paused,start),195*60);
console.log('PASS: focus deadlines, session transitions, missed-tick catch-up, zero breaks, pause, final completion, deterministic log IDs and ETA.');
