const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const path = require('node:path');
const filename = path.resolve('lib/refinements.ts');
const mod = new Module(filename, module);
mod._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
const {financialTotals,classifications,nextReviewDate,reviewDue,refinementDefaults}=mod.exports;
const rows=[{type:'Income',amount:10000},{type:'Expense',classification:'Need',amount:3000},{type:'Expense',classification:'Want',amount:1000},{type:'Savings',amount:2000},{type:'Investment',amount:500},{type:'Giving',amount:200},{type:'Expense',classification:'Savings',amount:300}];
assert.deepEqual(financialTotals(rows),{income:10000,expenses:4200,savings:2800,remaining:3000});
assert.deepEqual(classifications(rows),{Need:3000,Want:1000,Savings:2800,Unclassified:200});
assert.equal(financialTotals([{type:'Expense',amount:100}]).remaining,-100);
assert.equal(nextReviewDate('2026-01-31','Monthly'),'2026-02-28');
assert.equal(nextReviewDate('2028-01-31','Monthly'),'2028-02-29');
assert.equal(nextReviewDate('2026-11-30','Quarterly'),'2027-02-28');
assert.equal(nextReviewDate('2026-12-28','Weekly'),'2027-01-04');
const data=refinementDefaults();assert.equal(reviewDue(data,'2026-09-17'),true);
data.reviews=[{date:'2026-09-17'}];assert.equal(reviewDue(data,'2026-10-16'),false);assert.equal(reviewDue(data,'2026-10-17'),true);
data.reviewSchedule.enabled=false;assert.equal(reviewDue(data,'2027-01-01'),false);
console.log('PASS: remaining balance, savings classifications, legacy transactions, negative balances, review cadence and month-end clamping.');
