const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'en-US'});page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.LIFE_EDIT_URL||'http://localhost:3004';
 const visit=async route=>{await page.goto(base+route);await page.locator('.le-content').waitFor();};
 const click=async name=>page.getByRole('button',{name,exact:true}).first().click();
 const fill=async(name,value)=>page.getByLabel(name,{exact:true}).fill(String(value));
 const select=async(name,value)=>page.getByLabel(name,{exact:true}).selectOption(value);
 const tab=async name=>page.getByRole('tab',{name,exact:true}).click();
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('life-edit-preview-v2')));
 const upload=async()=>{const buffer=await page.screenshot();await page.getByLabel('Upload image',{exact:true}).setInputFiles({name:'progress.png',mimeType:'image/png',buffer});await page.getByRole('dialog').locator('img').waitFor();};
 fs.mkdirSync('test-results',{recursive:true});
 try {
  await visit('/fitness');assert.deepEqual(await page.getByRole('tab').allTextContents(),['Progress','Workouts','Exercise Library','Plans','Settings']);await page.getByText('Current weight',{exact:true}).waitFor();
  await tab('Settings');await fill('Goal weight (kg)',65);await tab('Progress');
  for(const [date,weight,waist] of [['2026-08-01',72,82],['2026-09-01',70,80]]){await click('Add progress entry');await fill('Progress date',date);await fill('Body weight (kg)',weight);await fill('Waist (cm)',waist);await click('Save progress entry');}
  await page.getByRole('heading',{name:'Compare your progress',exact:true}).waitFor();await page.getByRole('img',{name:/Weight trend:/}).waitFor();assert.equal((await saved()).goalWeight,65);
  await click('Add progress photo');await fill('Photo title','September progress');await upload();await click('Save photo');await page.reload();await page.getByRole('img',{name:'September progress',exact:true}).waitFor();assert.equal(await page.getByRole('img',{name:'September progress',exact:true}).evaluate(i=>i.complete&&i.naturalWidth>0),true);
  await click('Edit September progress');await fill('Photo notes','Steady progress');await click('Save photo');await click('Delete September progress');await click('Undo delete');assert.equal((await saved()).fitnessPhotos[0].notes,'Steady progress');
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v4-fitness.png',fullPage:true});console.log('PASS: fitness default tabs, progress trends, comparisons, goal weight, image persistence and CRUD/undo.');
  await visit('/finance');await tab('Budget');await click('Add budget');await select('Category','Food');await fill('Budget amount',3000);await click('Save budget');assert.equal((await saved()).transactions.length,0);assert.match(await page.getByRole('row').filter({hasText:'Food'}).innerText(),/0[.,]00/);
  await tab('Transactions');for(const [title,type,classification,amount] of [['Salary','Income','Need',10000],['Groceries','Expense','Need',1750],['Entertainment','Expense','Want',500],['Emergency fund','Savings','Savings',2000]]){await click('Add transaction');await fill('Description',title);await select('Type',type);if(!['Income','Savings'].includes(type))await select('Transaction classification',classification);if(type!=='Income')await select('Category',type==='Savings'?'Savings':'Food');await fill('Amount',amount);await click('Save transaction');}
  await tab('Budget');assert.match(await page.getByRole('row').filter({hasText:'Food'}).innerText(),/2[,\s]250[.,]00/);await tab('Overview');await page.getByText(/R 5[,\s]000[.,]00/,{exact:true}).first().waitFor();await page.getByRole('img',{name:/Spending distribution/}).waitFor();
  await tab('Guidance');await page.getByLabel('Show optional budget guidance').check();await page.getByText(/Actual: R 1[,\s]750[.,]00/,{exact:true}).waitFor();await fill('Needs (%)',60);await fill('Wants (%)',20);await click('Save allocation');assert.equal((await saved()).allocation.needs,60);
  await tab('Transactions');await click('Edit Groceries');await fill('Amount',20000);await click('Save transaction');await tab('Overview');await page.getByText(/R -12[,\s]500[.,]00/,{exact:true}).first().waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v4-finance.png',fullPage:true});console.log('PASS: separate budgets, classifications, allocation actuals and negative remaining balances.');
  await visit('/social');await click('Add relationship');await fill('Name','Sam');await select('Relationship type','Friends');await fill('Last contact date','2026-09-17');await fill('Conversation notes','New job');await fill('Shared or monthly connection goal','Monthly coffee');await fill('Gift ideas','A book');await click('Save relationship');await click('Edit Sam');await fill('Important memories','Graduation');await click('Save relationship');await click('Delete Sam');await click('Undo delete');assert.equal((await saved()).relationships[0].memories,'Graduation');
  await visit('/life-edit');await click('Add Custom Goal');await fill('Goal title','A meaningful career');await page.getByRole('dialog').getByRole('button',{name:'Personal Growth',exact:true}).click();await click('Save goal');await tab('Vision Board');await click('Add vision item');await fill('Title','Creative future');await fill('Motivation notes','Make something meaningful');await select('Future goal',{label:'A meaningful career'});await upload();await click('Save vision item');await page.reload();await tab('Vision Board');await page.getByRole('img',{name:'Creative future',exact:true}).waitFor();await click('Edit Creative future');await fill('Title','Creative life');await click('Save vision item');await click('Delete Creative life');await click('Undo delete');assert.ok((await saved()).board[0].goalId);console.log('PASS: relationship details and vision images, goal links, persistence, edit/delete/undo.');
  await visit('/insights');await select('Review frequency','Weekly');for(const [date,rating] of [['2026-08-01',5],['2026-09-01',7]]){await click('Life balance review');await fill('Review date',date);await fill('Physical rating',rating);await click('Save review');}await page.getByText('Physical +2',{exact:true}).waitFor();await click('Edit review 2026-09-01');await fill('Review notes','More consistent');await click('Save review');await click('Delete review 2026-09-01');await click('Undo delete');await page.getByRole('heading',{name:'What contributes to your pillars'}).waitFor();assert.equal((await saved()).reviews.length,2);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v4-insights.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});for(const route of ['/fitness','/finance','/social','/life-edit','/insights']){await visit(route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Overflow: '+route);}await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v4-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: review history, improvement calculations, edit/delete/undo, mobile layout and zero runtime errors.');
 }catch(e){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/v4-failure.png',fullPage:true});console.error(await page.locator('body').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
