"use client";
import { useState } from "react";
import { BudgetBreakdown } from "./budget-breakdown";
import { AlertTriangle, CalendarRange, Check, Plus, RotateCcw, XCircle } from "lucide-react";
import { budgetGuidanceSummary, financialTotals, budgetAllocation, classifications, financeCalendarSummary, financeEventDate, financeEventLabel, isPlannedFinanceTransaction, isSavings, type Classification } from "@/lib/refinements";
import { useLife, uid, today, type LifeData } from "@/lib/life-store";
import { Button, Card, Empty, Field, Heading, Modal, RecordActions, SaveButton, Tabs, Progress } from "./workspace-ui";
import { CategoryManager, RecordManager } from "./record-manager";

const colors: Record<string,string> = { Income:"#3f7ea8", Expense:"#bd5364", Savings:"#5f9369", Remaining:"#8e7ac6", Investment:"#c69a42", Giving:"#b5737a" };
const categoryPalette: Record<string,string> = {
  Housing:"#4f7fa4", Utilities:"#8e7ac6", Food:"#c75469", Transport:"#d39a3f", Entertainment:"#9d7bc7",
  Savings:"#5f9369", Investments:"#4d8f78", Health:"#d47983", Giving:"#b5737a"
};
const chartColors = ["#c75469", "#d39a3f", "#5f9369", "#8e7ac6", "#4f7fa4", "#d47983", "#4d8f78", "#b5737a"];
type Transaction = LifeData["transactions"][number];
type Budget = LifeData["budgets"][number];
type EventKind = "Income" | "Expense" | "Savings" | "Budget Event" | "Scheduled Payment";
type ScheduledStatus = "Upcoming" | "Paid" | "Missed";
type RecurrenceFrequency = NonNullable<Transaction["recurrenceFrequency"]>;
const niceDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"});
const scheduledStatus = (transaction: Transaction, activeDate: string): ScheduledStatus => transaction.paid ? "Paid" : transaction.status === "Missed" || (Boolean(transaction.dueDate) && financeEventDate(transaction) < activeDate) ? "Missed" : "Upcoming";
const eventKind = (transaction: Transaction): EventKind => transaction.type === "Income" ? "Income" : isSavings(transaction) ? "Savings" : transaction.plannedDate || transaction.dueDate || transaction.status || transaction.recurring ? "Scheduled Payment" : "Expense";
const recurrenceLabel = (transaction: Transaction) => transaction.recurring ? `Repeats every ${transaction.recurrenceInterval ?? 1} ${String(transaction.recurrenceFrequency ?? "Monthly").toLowerCase()}${(transaction.recurrenceInterval ?? 1) === 1 ? "" : "s"}` : "";
const addMonths = (date: Date, months: number) => { const next = new Date(date); const day = next.getDate(); next.setDate(1); next.setMonth(next.getMonth() + months); next.setDate(Math.min(day, new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate())); return next; };
const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function occurrenceDates(transaction: Transaction, start: string, end: string) {
  const first = transaction.recurrenceStart || transaction.plannedDate || transaction.dueDate || transaction.date;
  if (!transaction.recurring) return financeEventDate(transaction) >= start && financeEventDate(transaction) <= end ? [financeEventDate(transaction)] : [];
  const interval = Math.max(1, transaction.recurrenceInterval || 1);
  const frequency = transaction.recurrenceFrequency || "Monthly";
  const limit = transaction.recurrenceEnd && transaction.recurrenceEnd < end ? transaction.recurrenceEnd : end;
  const dates: string[] = [];
  let cursor = new Date(`${first}T12:00:00`);
  const stop = new Date(`${limit}T12:00:00`);
  for (let guard = 0; cursor <= stop && guard < 260; guard++) {
    const value = iso(cursor);
    if (value >= start && value <= end) dates.push(value);
    if (frequency === "Weekly") cursor.setDate(cursor.getDate() + 7 * interval);
    else if (frequency === "Biweekly") cursor.setDate(cursor.getDate() + 14 * interval);
    else if (frequency === "Monthly") cursor = addMonths(cursor, interval);
    else if (frequency === "Quarterly") cursor = addMonths(cursor, 3 * interval);
    else cursor = addMonths(cursor, 12 * interval);
  }
  return dates;
}
export function PaydayCard({ guidance, money, className = "" }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string; className?: string }) {
  return <Card className={`le-payday-card ${className}`.trim()}><div><p className="le-eyebrow">Next payday</p><h2>{niceDate(guidance.nextPayday)}</h2><p className="le-muted">Current cycle: {niceDate(guidance.cycleStart)} to {niceDate(guidance.cycleEnd)}</p></div><div className="le-payday-countdown"><strong>{guidance.daysUntilPayday}</strong><span>{guidance.daysUntilPayday === 1 ? "day" : "days"} remaining</span></div><div className="le-payday-daily"><span>Suggested daily budget</span><strong>{money(Math.max(0,guidance.todayRemaining))}</strong></div></Card>;
}
function EnvelopesView({ guidance, money, selectedWeekStart, onSelectWeek }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string; selectedWeekStart: string; onSelectWeek: (weekStart: string) => void }) {
  const { update } = useLife();
  const [planning,setPlanning]=useState(false);
  const [calendar,setCalendar]=useState(false);
  const [draft,setDraft]=useState<Record<string,number>>({});
  const [calc,setCalc]=useState(`${Math.round(guidance.monthlyBudget)} / ${guidance.weekEnvelopes.length || 1}`);
  const calcResult=(()=>{try{const clean=calc.replace(/÷/g,"/").replace(/x/gi,"*").replace(/[^0-9+\-*/(). ]/g,"");const value=Function(`"use strict";return (${clean||0})`)();return Number.isFinite(value)?Number(value):0;}catch{return 0;}})();
  const openPlanner=()=>{setDraft(Object.fromEntries(guidance.weekEnvelopes.map(w=>[w.start,w.budget])));setPlanning(true);};
  const evenSplit=()=>{const count=guidance.weekEnvelopes.length;if(!count)return {};const totalCents=Math.max(0,Math.round(guidance.monthlyBudget*100));const base=Math.floor(totalCents/count);const extra=totalCents-base*count;return Object.fromEntries(guidance.weekEnvelopes.map((w,i)=>[w.start,(base+(i<extra?1:0))/100]));};
  const persist=(values:Record<string,number>)=>update(d=>({...d,weeklyBudgetPlans:[...d.weeklyBudgetPlans.filter(p=>!(p.currency===guidance.currency&&p.month===guidance.month)),...guidance.weekEnvelopes.map(w=>({id:d.weeklyBudgetPlans.find(p=>p.currency===guidance.currency&&p.month===guidance.month&&p.weekStart===w.start)?.id??uid(),month:guidance.month,weekStart:w.start,weekEnd:w.end,currency:guidance.currency,amount:Number(values[w.start]??w.budget)}))]}));
  const split=()=>{const value=Math.max(0,calcResult);const values=value>0?Object.fromEntries(guidance.weekEnvelopes.map(w=>[w.start,value])):evenSplit();setDraft(values);persist(values);};
  const save=()=>{persist(draft);setPlanning(false);};
  return <div className="le-grid-main"><Card className="le-envelope-card"><div className="le-row"><div><p className="le-eyebrow">Weekly envelopes</p><h2>Pay-cycle money, divided into calm weekly lanes.</h2></div><div className="le-inline"><Button secondary onClick={()=>setCalendar(!calendar)}><CalendarRange size={16}/>Calendar view</Button><Button onClick={openPlanner}>Envelope planning</Button></div></div>{calendar&&<div className="le-month-calendar"><h3>{niceDate(guidance.cycleStart)} to {niceDate(guidance.cycleEnd)}</h3>{guidance.weekEnvelopes.map(week=><button key={week.start} type="button" className={selectedWeekStart===week.start?"is-selected":""} onClick={()=>onSelectWeek(week.start)}><strong>{week.label}</strong><span>{week.start.slice(5)} to {week.end.slice(5)}</span></button>)}</div>}<div className="le-envelope-grid">{guidance.weekEnvelopes.map(week=>{const over=Math.max(0,-week.remaining);return <button type="button" key={week.label} onClick={()=>onSelectWeek(week.start)} className={`${week.start<=guidance.date&&week.end>=guidance.date?"is-current":""} ${selectedWeekStart===week.start?"is-selected":""}`}><span>{week.label}</span><h3>{money(Math.max(0,week.remaining))}</h3><p>{week.start.slice(5)} to {week.end.slice(5)}</p><small>{money(week.budget)} guide · {money(week.spent)} used{week.scheduled>0?` · ${money(week.scheduled)} scheduled`: ""}</small><Progress value={week.budget?week.spent/week.budget*100:0}/>{over>0&&<em>{money(over)} above this week. Daily guidance adjusts forward.</em>}</button>;})}</div></Card>{planning&&<Card className="le-envelope-planner"><p className="le-eyebrow">Envelope planning panel</p><h2>Split this pay cycle your way.</h2><dl className="le-record-details"><div><dt>Cycle Budget</dt><dd>{money(guidance.monthlyBudget)}</dd></div><div><dt>Available</dt><dd>{money(guidance.monthlyBudget)}</dd></div><div><dt>Number of weeks</dt><dd>{guidance.weekEnvelopes.length}</dd></div></dl><div className="le-mini-calculator"><Field label="Calculator"><input value={calc} onChange={e=>setCalc(e.target.value)} /></Field><strong>= {money(calcResult)}</strong></div><div className="le-inline"><Button secondary onClick={split}>Use Calculator Result For Each Week</Button><Button onClick={save} className="le-compact-action">Save split</Button></div><div className="le-envelope-edit-list">{guidance.weekEnvelopes.map(week=><Field key={week.start} label={`${week.label} · ${week.start.slice(5)} to ${week.end.slice(5)}`}><input type="number" min="0" step="0.01" value={(draft[week.start]??week.budget)>0?(draft[week.start]??week.budget):""} placeholder="0.00" onChange={e=>setDraft({...draft,[week.start]:e.target.value===""?0:Number(e.target.value)})}/></Field>)}</div></Card>}</div>;
}
function BudgetHomeView({ guidance, income, budgets, money }: { guidance: ReturnType<typeof budgetGuidanceSummary>; income: number; budgets: Budget[]; money: (value: number) => string }) {
  const totalBudgeted=budgets.reduce((sum,b)=>sum+b.amount,0);
  const remaining=income-totalBudgeted;
  const warning=totalBudgeted>income;
  return <div className="le-budget-home"><Card className={warning?"le-budget-warning":""}><p className="le-eyebrow">Monthly Budget</p><div className="le-grid-four">{[["Income",income],["Total Budgeted",totalBudgeted],["Remaining Budget",remaining],["Envelope Progress",guidance.monthlyBudget?guidance.monthlySpent/guidance.monthlyBudget*100:0]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{String(label)==="Envelope Progress"?`${Math.round(Number(value))}%`:money(Number(value))}</strong></div>)}</div>{warning&&<div className="le-insight-list mt-5"><p>Your planned expenses exceed your income by {money(totalBudgeted-income)}.</p><p>Recommendations: reduce Fun Budget, reduce Maintenance Budget, adjust envelope targets, or delay non-essential spending.</p></div>}</Card><Card className="mt-6"><p className="le-eyebrow">Envelope progress</p><div className="le-envelope-grid">{guidance.weekEnvelopes.map(week=><button type="button" key={week.start}><span>{week.label}</span><h3>{money(Math.max(0,week.remaining))}</h3><small>{money(week.budget)} planned · {money(week.scheduled)} scheduled</small><Progress value={week.budget?(week.spent+week.scheduled)/week.budget*100:0}/></button>)}</div></Card></div>;
}
function BudgetDailyPlanView({ guidance, money }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string }) {
  const { data, update } = useLife();
  const [plan,setPlan]=useState<LifeData["dailyBudgetPlans"][number]|null>(null);
  const plans=data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date>=guidance.cycleStart&&p.date<=guidance.cycleEnd).sort((a,b)=>a.date.localeCompare(b.date));
  const addPlan=()=>setPlan({id:uid(),date:guidance.date,category:data.categories[0]??"",amount:0,currency:data.currency,note:"",actualAmount:0,completed:false});
  const savePlan=()=>{if(!plan)return;update(d=>({...d,dailyBudgetPlans:[...d.dailyBudgetPlans.filter(p=>p.id!==plan.id),plan]}));setPlan(null);};
  return <><div className="le-row mb-5"><h2>Daily Spending Plan</h2><Button onClick={addPlan}><Plus size={16}/>Plan item</Button></div><Card>{plans.length?plans.map(p=>{const actual=p.actualAmount??0;return <div key={p.id} className={`le-planned-spend-item ${p.completed?"is-paid":""}`}><div><span>{p.note||p.category||"Planned item"}</span><small>{niceDate(p.date)} · Planned {money(p.amount)} · Actual {money(actual)} · Difference {money(actual-p.amount)}</small></div><div className="le-inline"><button type="button" className="le-text-action" onClick={()=>update(d=>({...d,dailyBudgetPlans:d.dailyBudgetPlans.map(x=>x.id===p.id?{...x,completed:!x.completed}:x)}))}>{p.completed?"Undo complete":"Mark Completed"}</button><button type="button" className="le-text-action" onClick={()=>setPlan(p)}>Edit</button><button type="button" className="le-text-action" onClick={()=>update(d=>({...d,dailyBudgetPlans:d.dailyBudgetPlans.filter(x=>x.id!==p.id)}))}>Delete</button></div></div>}):<Empty title="No daily spending planned." action="Plan spending" onClick={addPlan}/>}</Card>{plan&&<Modal title="Daily spending item" close={()=>setPlan(null)}><form onSubmit={e=>{e.preventDefault();savePlan();}}><Field label="Item"><input required value={plan.note} onChange={e=>setPlan({...plan,note:e.target.value})}/></Field><Field label="Category"><select value={plan.category} onChange={e=>setPlan({...plan,category:e.target.value})}>{data.categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Date"><input type="date" required value={plan.date} onChange={e=>setPlan({...plan,date:e.target.value})}/></Field><Field label="Planned spend"><input type="number" min="0.01" step="0.01" required value={plan.amount>0?plan.amount:""} onChange={e=>setPlan({...plan,amount:e.target.value===""?0:Number(e.target.value)})}/></Field><Field label="Actual spend"><input type="number" min="0" step="0.01" value={(plan.actualAmount??0)>0?plan.actualAmount:""} onChange={e=>setPlan({...plan,actualAmount:e.target.value===""?0:Number(e.target.value)})}/></Field><label className="le-check-row"><input type="checkbox" checked={Boolean(plan.completed)} onChange={e=>setPlan({...plan,completed:e.target.checked})}/><span>Completed</span><small>Variance {money((plan.actualAmount??0)-plan.amount)}</small></label><SaveButton>Save plan item</SaveButton></form></Modal>}</>;
}
function BudgetCalendarView({ data, guidance, money }: { data: LifeData; guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string }) {
  const planned=data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date>=guidance.cycleStart&&p.date<=guidance.cycleEnd);
  return <Card className="le-finance-calendar-card"><div className="le-row"><div><p className="le-eyebrow">Budget Calendar</p><h2>Planned money only.</h2></div><CalendarRange size={24}/></div><div className="le-finance-agenda" style={{display:"block"}}>{guidance.weekEnvelopes.map(week=><section key={week.start}><h3>{week.label}: {week.start.slice(5)} to {week.end.slice(5)}</h3><div className="le-agenda-item"><span>Envelope allocation</span><small>Weekly spending plan</small><strong>{money(week.budget)}</strong></div>{planned.filter(p=>p.date>=week.start&&p.date<=week.end).map(p=><div className="le-agenda-item" key={p.id}><span>{p.note||p.category}</span><small>Planned expense · {niceDate(p.date)}</small><strong>{money(p.amount)}</strong></div>)}</section>)}</div></Card>;
}
function FinanceCalendarView({ data, activeDate, money, openTransaction, markStatus, deleteTransaction }: { data: LifeData; activeDate: string; money: (value: number) => string; openTransaction: (transaction: Transaction) => void; markStatus: (transaction: Transaction, status: ScheduledStatus) => void; deleteTransaction: (id: string) => void }) {
  const [selectedDate,setSelectedDate]=useState<string|null>(null);
  const summary=financeCalendarSummary(data,activeDate,data.currency);
  const first=new Date(`${summary.cycleStart}T12:00:00`);
  const leading=(first.getDay()+6)%7;
  const cells=[...Array.from({length:leading},(_,i)=>({key:`blank-${i}`,blank:true as const})),...summary.daily.map(day=>({key:day.date,blank:false as const,day}))];
  const transactions=data.transactions.filter(t=>t.currency===data.currency);
  const eventRows=[...transactions.flatMap(t=>occurrenceDates(t,summary.cycleStart,summary.cycleEnd).map(date=>({id:t.id,date,title:t.title,type:eventKind(t),label:financeEventLabel(t),amount:t.amount,category:t.category,transaction:t as Transaction|null}))),...data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date>=summary.cycleStart&&p.date<=summary.cycleEnd).map(p=>({id:p.id,date:p.date,title:p.note||p.category||"Planned spend",type:"Budget Event" as EventKind,label:"Budget Event",amount:p.amount,category:p.category,transaction:null as Transaction|null}))].sort((a,b)=>a.date.localeCompare(b.date)||b.amount-a.amount);
  const scheduled=eventRows.filter(row=>row.transaction&&row.transaction.type!=="Income"&&(row.transaction.plannedDate||row.transaction.dueDate||row.transaction.status||row.transaction.recurring)).map(row=>({...row.transaction!,date:row.date,dueDate:row.date}));
  const grouped=eventRows.reduce<Record<string,typeof eventRows>>((groups,row)=>({...groups,[row.date]:[...(groups[row.date]??[]),row]}),{});
  const agendaDates=Object.keys(grouped).sort((a,b)=>a.localeCompare(b));
  const selectedEvents=selectedDate?grouped[selectedDate]??[]:[];
  return <div className="le-finance-calendar-view">
    {summary.insights.length>0&&<Card className="le-cashflow-insights mb-6"><div className="le-row"><div><p className="le-eyebrow">Cash flow insights</p><h2>Plan ahead before the money moves.</h2></div><AlertTriangle size={24}/></div><div className="le-insight-list">{summary.insights.map(insight=><p key={insight}>{insight.replace(/\d+(?= of planned spending)/,value=>money(Number(value)))}</p>)}</div></Card>}
    <div className="le-grid-main"><Card className="le-finance-calendar-card"><div className="le-row"><div><p className="le-eyebrow">Finance calendar</p><h2>{niceDate(summary.cycleStart)} to {niceDate(summary.cycleEnd)}</h2></div><CalendarRange size={24}/></div><div className="le-calendar-weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><span key={day}>{day}</span>)}</div><div className="le-finance-calendar-grid">{cells.map(cell=>cell.blank?<div key={cell.key} aria-hidden="true"/>:<button type="button" key={cell.key} className={`${cell.day.date===activeDate?"is-today":""} ${summary.highSpendDays.includes(cell.day.date)?"is-high-spend":""}`} onClick={()=>setSelectedDate(cell.day.date)}><strong>{Number(cell.day.date.slice(8))}</strong><span>{cell.day.totalOutflow>0?money(cell.day.totalOutflow):" "}</span>{cell.day.income>0&&<i className="is-income">Income</i>}{cell.day.planned>0&&<i>Reserved {money(cell.day.planned)}</i>}{cell.day.eventCount>0&&<small>{cell.day.eventCount} event{cell.day.eventCount===1?"":"s"}</small>}</button>)}</div><div className="le-finance-agenda"><p className="le-eyebrow">Agenda</p>{agendaDates.length?agendaDates.map(date=><section key={date}><h3>{date===activeDate?"Today":niceDate(date)}</h3>{grouped[date].map(row=><button type="button" key={`${row.id}:${row.type}`} className="le-agenda-item" onClick={()=>row.transaction?openTransaction(row.transaction):setSelectedDate(date)}><span>{row.title}</span><small>{row.type} · {row.category}</small><strong>{money(row.amount)}</strong></button>)}</section>):<Empty title="No finance events in this pay cycle." />}</div></Card>
    <div className="le-calendar-side"><Card><p className="le-eyebrow">Weekly Spending Overview</p>{summary.weekly.map(week=><div key={week.start} className="le-calendar-week-row"><div><strong>{week.label}</strong><small>{week.start.slice(5)} to {week.end.slice(5)}</small></div><span>{money(week.totalOutflow)}</span></div>)}</Card><Card className="mt-6"><p className="le-eyebrow">Upcoming major expenses</p>{summary.upcomingMajorExpenses.length?summary.upcomingMajorExpenses.map(item=><div key={item.id} className="le-calendar-event-row"><div><strong>{item.title}</strong><small>{niceDate(item.date)} · {item.category}</small></div><span>{money(item.amount)}</span></div>):<p className="le-muted">No major planned expenses remaining in this pay cycle.</p>}</Card></div></div>
    <Card className="mt-6 le-scheduled-payments"><div className="le-row"><div><p className="le-eyebrow">Scheduled payments</p><h2>Name, category, amount, due date, and status.</h2></div></div>{scheduled.length?scheduleRows(scheduled,activeDate,money,openTransaction,markStatus,deleteTransaction):<Empty title="No scheduled payments in this pay cycle." />}</Card>
    {selectedDate&&<Modal title={niceDate(selectedDate)} close={()=>setSelectedDate(null)}><div className="le-day-event-list">{selectedEvents.length?selectedEvents.map(row=><div key={`${row.id}:${row.type}`} className={`le-event-detail is-${row.type.toLowerCase().replaceAll(" ","-")}`}><button type="button" onClick={()=>row.transaction&&openTransaction(row.transaction)} disabled={!row.transaction}><strong>{row.title}</strong><small>{row.type} · {row.category}</small></button><span>{money(row.amount)}</span>{row.transaction&&<div className="le-inline"><button type="button" className="le-text-action" onClick={()=>openTransaction(row.transaction!)}>Edit</button>{row.type==="Scheduled Payment"&&<><button type="button" className="le-text-action" onClick={()=>markStatus(row.transaction!,"Paid")}>Mark Paid</button><button type="button" className="le-text-action" onClick={()=>markStatus(row.transaction!,"Missed")}>Mark Missed</button></>}<button type="button" className="le-text-action" onClick={()=>deleteTransaction(row.transaction!.id)}>Delete</button></div>}</div>):<Empty title="No events for this day." />}</div></Modal>}</div>;
}
function scheduleRows(rows: Transaction[], activeDate: string, money: (value: number) => string, openTransaction: (transaction: Transaction) => void, markStatus: (transaction: Transaction, status: ScheduledStatus) => void, deleteTransaction: (id: string) => void) {
  return <div className="le-scheduled-list">{rows.sort((a,b)=>financeEventDate(a).localeCompare(financeEventDate(b))).map(t=>{const status=scheduledStatus(t,activeDate);return <div className={`le-scheduled-row is-${status.toLowerCase()}`} key={`${t.id}:${financeEventDate(t)}`}><button type="button" className="le-scheduled-main" onClick={()=>openTransaction(t)}><strong>{t.title}</strong><small>{t.category} · Due {niceDate(financeEventDate(t))}{t.recurring?` · ${recurrenceLabel(t)}`:""}</small></button><span>{money(t.amount)}</span><em>{status}</em><div className="le-inline"><button type="button" className="le-text-action" onClick={()=>markStatus(t,"Paid")} disabled={status==="Paid"}><Check size={14}/>Paid</button><button type="button" className="le-text-action" onClick={()=>markStatus(t,"Missed")} disabled={status==="Missed"}><XCircle size={14}/>Missed</button>{status!=="Upcoming"&&<button type="button" className="le-text-action" onClick={()=>markStatus(t,"Upcoming")}><RotateCcw size={14}/>Undo</button>}<RecordActions name={t.title} edit={()=>openTransaction(t)} remove={()=>deleteTransaction(t.id)}/></div></div>;})}</div>;
}
function FinancialEventsView({ data, guidance, money, openTransaction }: { data: LifeData; guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string; openTransaction: (transaction: Transaction) => void }) {
  const [filter,setFilter]=useState<EventKind|"All">("All");
  const [query,setQuery]=useState("");
  const [sort,setSort]=useState<"date"|"amount"|"type">("date");
  const rows=[
    ...data.transactions.filter(t=>t.currency===data.currency).flatMap(t=>occurrenceDates(t,guidance.cycleStart,guidance.cycleEnd).map(date=>({id:t.id,date,title:t.title,type:eventKind(t),amount:t.amount,category:t.category,transaction:t as Transaction|null}))),
    ...data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date>=guidance.cycleStart&&p.date<=guidance.cycleEnd).map(p=>({id:p.id,date:p.date,title:p.note||p.category||"Planned spend",type:"Budget Event" as EventKind,amount:p.amount,category:p.category,transaction:null as Transaction|null}))
  ].filter(row=>(filter==="All"||row.type===filter)&&`${row.title} ${row.category} ${row.type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="amount"?b.amount-a.amount:sort==="type"?a.type.localeCompare(b.type)||a.date.localeCompare(b.date):a.date.localeCompare(b.date)||b.amount-a.amount);
  return <Card className="le-financial-events"><div className="le-row"><div><p className="le-eyebrow">Financial Events</p><h2>Income, expenses, savings, budget events, and scheduled payments.</h2></div></div><div className="le-event-controls"><input aria-label="Search financial events" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events"/><select aria-label="Filter financial events" value={filter} onChange={e=>setFilter(e.target.value as EventKind|"All")}><option>All</option>{(["Income","Expense","Savings","Budget Event","Scheduled Payment"] as const).map(item=><option key={item}>{item}</option>)}</select><select aria-label="Sort financial events" value={sort} onChange={e=>setSort(e.target.value as "date"|"amount"|"type")}><option value="date">Sort by date</option><option value="amount">Sort by amount</option><option value="type">Sort by type</option></select></div><div className="le-table-scroll"><table><thead><tr><th>Date</th><th>Event</th><th>Type</th><th>Category</th><th>Amount</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.id}:${row.type}`} className={`le-event-row is-${row.type.toLowerCase().replaceAll(" ","-")}`}><td>{niceDate(row.date)}</td><th>{row.transaction?<button type="button" className="le-table-category" onClick={()=>openTransaction(row.transaction!)}>{row.title}</button>:row.title}</th><td>{row.type}</td><td>{row.category}</td><td>{money(row.amount)}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty title="No financial events match your filters." />}</Card>;
}
function FinanceOverviewView({ data, income, expenses, savings, availableBalance, allocationActual, series, breakdown, total, pie, categoryColor, money, allocationBalance }: { data: LifeData; income: number; expenses: number; savings: number; availableBalance: number; allocationActual: ReturnType<typeof classifications>; series: { month: string; values: number[]; classification: ReturnType<typeof classifications> }[]; breakdown: { name: string; value: number }[]; total: number; pie: string; categoryColor: (name: string, index: number) => string; money: (value: number) => string; allocationBalance: ReturnType<typeof budgetAllocation> }) {
  return <><Card className="le-finance-primary"><p className="le-eyebrow">Actual money</p><div className="le-grid-four">{[["Available Balance",availableBalance],["Income",income],["Expenses",expenses],["Savings",savings]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div></Card><details className="le-overview-section mt-6" open><summary>Needs / Wants / Savings</summary><div className="le-grid-three mt-4">{(["needs","wants","savings"] as const).map(key=>{const label=key[0].toUpperCase()+key.slice(1);const actual=allocationActual[key==="needs"?"Need":key==="wants"?"Want":"Savings"];return <Card key={key}><p className="le-eyebrow">{label}</p><p className="le-metric">{money(actual)}</p><Progress value={income?actual/(income*data.allocation[key]/100)*100:0}/><p className="le-muted mt-3">Current allocation · {data.allocation[key]}% target</p></Card>;})}</div><div className="le-table-scroll mt-5"><table><thead><tr><th>Month</th><th>Needs</th><th>Wants</th><th>Savings</th><th>Unclassified</th></tr></thead><tbody>{series.map(s=>{const sum=Object.values(s.classification).reduce((a,b)=>a+b,0);return <tr key={s.month}><th>{s.month}</th>{Object.values(s.classification).map((v,i)=><td key={i}>{sum?(v/sum*100).toFixed(1)+"%":"-"}</td>)}</tr>;})}</tbody></table></div></details><details className="le-overview-section mt-6"><summary>Financial Health</summary><dl className="le-record-details mt-4">{[["Savings Rate",income?`${(savings/income*100).toFixed(1)}%`:"No income recorded"],["Budget Performance",allocationBalance.overspent>0?`${money(allocationBalance.overspent)} over budget`:"Within current budget limits"],["Spending Consistency",expenses>income*.75?"High expense load":"Expense load is manageable"],["Reserved for budgets",money(allocationBalance.reserved)],["Spending outside budgets",money(allocationBalance.unbudgeted)],["Available to allocate",money(allocationBalance.available)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details><details className="le-overview-section mt-6"><summary>Spending By Category</summary><div className="mt-4">{!total?<Empty title="Add transactions to see your spending." />:<div className="le-pie-layout"><div className="le-pie" role="img" aria-label={`Spending distribution: ${breakdown.map(x=>`${x.name} ${money(x.value)}`).join(", ")}`} style={{background:`conic-gradient(${pie})`}}/><ul className="le-chart-legend">{breakdown.map((x,i)=><li key={x.name}><i style={{background:categoryColor(x.name,i)}}/><span>{x.name}</span><strong>{money(x.value)}</strong></li>)}</ul></div>}</div><div className="le-table-scroll mt-5"><table><thead><tr><th>Category</th><th>Amount</th><th>Share</th></tr></thead><tbody>{breakdown.map(row=><tr key={row.name}><th>{row.name}</th><td>{money(row.value)}</td><td>{total?(row.value/total*100).toFixed(1):0}%</td></tr>)}</tbody></table></div></details></>;
}
function PaymentToggle({ transaction, togglePaid }: { transaction: Transaction; togglePaid: (transaction: Transaction, paid: boolean) => void }) {
  if (transaction.type === "Income" || (!transaction.plannedDate && !transaction.dueDate)) return null;
  return <button type="button" className="le-payment-toggle" aria-pressed={Boolean(transaction.paid)} aria-label={`${transaction.paid ? "Mark unpaid" : "Mark paid"} ${transaction.title}`} title={transaction.paid ? "Paid off" : "Mark paid"} onClick={()=>togglePaid(transaction,!transaction.paid)}><Check size={16}/></button>;
}
export function FinanceWorkspace({ budgetModule = false }: { budgetModule?: boolean }) {
  const { data, update } = useLife(); const [tab,setTab]=useState(budgetModule?"Home":"Overview"); const [month,setMonth]=useState(today().slice(0,7)); const [selectedWeekStart,setSelectedWeekStart]=useState(""); const [draft,setDraft]=useState<Transaction|null>(null); const [budget,setBudget]=useState<Budget|null>(null); const [currencyOpen,setCurrencyOpen]=useState(false); const [error,setError]=useState("");
  const currency = data.currencies.find(c => c.code === data.currency) ?? { code: data.currency, symbol: data.currency };
  const money = (v:number) => `${currency.symbol} ${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const activeDate=month===today().slice(0,7)?today():`${month}-01`;
  const guidance=budgetGuidanceSummary(data,activeDate,data.currency);
  const cycleRange={start:guidance.cycleStart,end:guidance.cycleEnd};
  const entries = data.transactions.filter(t => t.currency === data.currency && financeEventDate(t) >= guidance.cycleStart && financeEventDate(t) <= guidance.cycleEnd); const budgets = data.budgets.filter(b => b.currency === data.currency && b.month === guidance.budgetMonth);
  const actualEntries=entries.filter(t=>t.type==="Income"||t.paid||!isPlannedFinanceTransaction(t,guidance.date)).filter(t=>t.status!=="Missed");
  const {income,expenses,savings}=financialTotals(actualEntries);
  const availableBalance=income-expenses-savings;
  const selectedWeek=guidance.weekEnvelopes.find(week=>week.start===selectedWeekStart) ?? guidance.weekEnvelopes.find(week=>guidance.date>=week.start&&guidance.date<=week.end) ?? guidance.weekEnvelopes[0];
  const allocationBalance=budgetAllocation(data.transactions,data.budgets,guidance.budgetMonth,data.currency,cycleRange);
  const allocationActual=classifications(actualEntries);
  const newTransaction = (category?:string) => setDraft({id:uid(),title:"",type:"Expense",classification:"",amount:0,category:category??data.categories[0]??"Other",currency:data.currency,date:guidance.date,recurring:false,recurrenceFrequency:"Monthly",recurrenceInterval:1,recurrenceStart:guidance.date});
  const newScheduledPayment = () => setDraft({id:uid(),title:"",type:"Expense",classification:"Need",amount:0,category:data.categories[0]??"Other",currency:data.currency,date:guidance.date,dueDate:guidance.date,paid:false,status:"Upcoming",recurring:false,recurrenceFrequency:"Monthly",recurrenceInterval:1,recurrenceStart:guidance.date});
  const editTransaction=(transaction:Transaction)=>setDraft({...transaction});
  const markStatus=(transaction:Transaction,status:ScheduledStatus)=>update(d=>({...d,transactions:d.transactions.map(t=>t.id===transaction.id?{...t,status,paid:status==="Paid",paidDate:status==="Paid"?guidance.date:undefined,date:status==="Paid"?guidance.date:(t.plannedDate||t.dueDate||t.date)}:t)}));
  const togglePaid=(transaction:Transaction,paid:boolean)=>markStatus(transaction,paid?"Paid":"Upcoming");
  const breakdown = [...new Set(actualEntries.filter(t=>t.type!=="Income").map(t=>isSavings(t) ? "Savings" : t.category))].map(name=>({name,value:actualEntries.filter(t=>t.type!=="Income" && (isSavings(t) ? "Savings" : t.category)===name).reduce((s,t)=>s+t.amount,0)})).filter(x=>x.value>0);
  const categoryColor=(name:string,index:number)=>categoryPalette[name] ?? chartColors[index%chartColors.length];
  const total=breakdown.reduce((s,x)=>s+x.value,0); let angle=0;
  const pie=breakdown.map((x,i)=>{const from=angle;angle+=x.value/total*360;return `${categoryColor(x.name,i)} ${from}deg ${angle}deg`;}).join(",");
  const months=Array.from({length:6},(_,i)=>{const d=new Date(`${month}-15T12:00:00`);d.setMonth(d.getMonth()-5+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;});
  const series=months.map(m=>{const range=budgetGuidanceSummary(data,`${m}-01`,data.currency);const rows=data.transactions.filter(t=>t.currency===data.currency&&financeEventDate(t)>=range.cycleStart&&financeEventDate(t)<=range.cycleEnd&&(t.type==="Income"||t.paid||!isPlannedFinanceTransaction(t,range.date))&&t.status!=="Missed");const v=financialTotals(rows);const balance=budgetAllocation(data.transactions,data.budgets,range.budgetMonth,data.currency,{start:range.cycleStart,end:range.cycleEnd});return {month:m,values:[v.income,v.expenses,v.savings,balance.available],classification:classifications(rows)};});
  const scheduledRows=data.transactions.filter(t=>t.currency===data.currency&&t.type!=="Income"&&(t.plannedDate||t.dueDate||t.status||t.recurring)).flatMap(t=>occurrenceDates(t,guidance.cycleStart,guidance.cycleEnd).map(date=>({...t,date,dueDate:date})));
  const financeTabs=["Overview","Calendar","Scheduled Payments","Transactions","Financial Events","Savings Goals","Categories"];
  const budgetTabs=["Home","Monthly Budget","Envelopes","Daily Spending","Weekly Plan","Calendar","Categories"];
  return <><Heading section={budgetModule?"Budget planning":"Financial reality"} title={budgetModule?"Plan where money should go.":"Track what actually happened."}><div className="le-finance-toolbar"><select aria-label="Currency" value={data.currency} onChange={e=>e.target.value==="custom"?setCurrencyOpen(true):update(d=>({...d,currency:e.target.value}))}>{data.currencies.map(c=><option key={c.code} value={c.code}>{c.code} · {c.name}</option>)}<option value="custom">+ Add Custom Currency</option></select><input aria-label="Payday day" type="number" min="1" max="31" required value={data.financeSettings?.payday ?? 25} onChange={e=>update(d=>({...d,financeSettings:{...(d.financeSettings??{payday:25,payFrequency:"Monthly"}),payday:Math.min(31,Math.max(1,Number(e.target.value)||25))}}))}/><select aria-label="Pay frequency" value={data.financeSettings?.payFrequency ?? "Monthly"} onChange={e=>update(d=>({...d,financeSettings:{...(d.financeSettings??{payday:25,payFrequency:"Monthly"}),payFrequency:e.target.value as "Monthly"}}))}><option>Monthly</option></select><input aria-label="Cycle anchor month" type="month" required value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}} /></div></Heading><div className="my-6"><Tabs items={budgetModule?budgetTabs:financeTabs} active={tab} onChange={setTab} /></div>
    {!budgetModule&&tab==="Overview"&&<FinanceOverviewView data={data} money={money} income={income} expenses={expenses} savings={savings} availableBalance={availableBalance} allocationActual={allocationActual} allocationBalance={allocationBalance} breakdown={breakdown} total={total} pie={pie} categoryColor={categoryColor} series={series}/>}
    {budgetModule&&tab==="Home"&&<BudgetHomeView guidance={guidance} income={income} budgets={budgets} money={money}/>}
    {!budgetModule&&tab==="Calendar"&&<FinanceCalendarView data={data} activeDate={guidance.date} money={money} openTransaction={editTransaction} markStatus={markStatus} deleteTransaction={id=>update(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))}/>}
    {budgetModule&&tab==="Calendar"&&<BudgetCalendarView data={data} guidance={guidance} money={money}/>}
    {!budgetModule&&tab==="Scheduled Payments"&&<><div className="le-row mb-5"><h2>Scheduled payments</h2><Button onClick={newScheduledPayment}><Plus size={16}/>Add scheduled payment</Button></div><Card className="le-scheduled-payments">{scheduledRows.length?scheduleRows(scheduledRows,guidance.date,money,editTransaction,markStatus,id=>update(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))):<Empty title="No scheduled payments in this pay cycle." action="Add scheduled payment" onClick={newScheduledPayment}/>}</Card></>}
    {!budgetModule&&tab==="Transactions"&&<><div className="le-row mb-5"><h2>Income and outgoings</h2><Button onClick={()=>newTransaction()}><Plus size={16}/>Add transaction</Button></div>{!entries.length?<Empty title="No transactions in this pay cycle." action="Add transaction" onClick={()=>newTransaction()}/>:<Card>{entries.map(t=><div key={t.id} className={`le-row le-log le-transaction-row ${t.paid?"is-paid":""}`}><div><strong>{t.title}</strong><p className="le-muted">{financeEventDate(t)} · {t.category} · {t.type}{t.type!=="Income"&&` · ${isSavings(t)?"Savings":t.classification||"Unclassified"}`}{t.plannedDate?` · planned ${t.plannedDate}`:""}{t.dueDate?` · due ${t.dueDate}`:""}{t.paid?` · paid${t.paidDate?` ${t.paidDate}`:""}`:""}{t.recurring?` · ${recurrenceLabel(t)}`:""}</p></div><div className="le-inline le-transaction-actions"><strong style={{color:colors[t.type]}}>{money(t.amount)}</strong><PaymentToggle transaction={t} togglePaid={togglePaid}/><RecordActions name={t.title} edit={()=>editTransaction(t)} remove={()=>update(d=>({...d,transactions:d.transactions.filter(x=>x.id!==t.id)}))}/></div></div>)}</Card>}</>}
    {!budgetModule&&tab==="Financial Events"&&<FinancialEventsView data={data} guidance={guidance} money={money} openTransaction={editTransaction}/>}
    {budgetModule&&tab==="Monthly Budget"&&<BudgetBreakdown key={`${guidance.budgetMonth}:${data.currency}`} budgets={budgets} entries={entries} money={money} categoryLimits={data.spendingLimits.categories} activeDate={guidance.date} plannedItems={data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date>=guidance.cycleStart&&p.date<=guidance.cycleEnd)} addBudget={()=>{setError("");setBudget({id:uid(),category:data.categories[0]??"Other",currency:data.currency,month:guidance.budgetMonth,amount:0});}} editBudget={b=>{setError("");setBudget(b);}} deleteBudget={id=>update(d=>({...d,budgets:d.budgets.filter(b=>b.id!==id)}))} addSpending={newTransaction} editTransaction={editTransaction} deleteTransaction={id=>update(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))} togglePaid={togglePaid}/>}
    {budgetModule&&tab==="Envelopes"&&<EnvelopesView guidance={guidance} money={money} selectedWeekStart={selectedWeek?.start??""} onSelectWeek={setSelectedWeekStart}/>}
    {budgetModule&&tab==="Daily Spending"&&<BudgetDailyPlanView guidance={guidance} money={money}/>}
    {budgetModule&&tab==="Weekly Plan"&&<EnvelopesView guidance={guidance} money={money} selectedWeekStart={selectedWeek?.start??""} onSelectWeek={setSelectedWeekStart}/>}

    {!budgetModule&&tab==="Savings Goals"&&<RecordManager collection="savingsGoals" title="Savings goals" singular="savings goal" fields={[{key:"title",label:"Goal name",required:true},{key:"target",label:"Target amount",type:"number",min:0.01,required:true},{key:"saved",label:"Amount saved",type:"number",min:0},{key:"currency",label:"Goal currency",type:"select",options:data.currencies.map(c=>c.code),initial:data.currency},{key:"due",label:"Target date",type:"date"}]}/>}
    {tab==="Categories"&&<CategoryManager categoryKey="categories" title="Budget categories"/>}
    {draft&&<Modal title={data.transactions.some(t=>t.id===draft.id)?"Edit transaction":"New transaction"} close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();const paid=Boolean(draft.paid&&draft.type!=="Income");const paidDate=paid?(draft.paidDate||draft.date||guidance.date):undefined;const saved={...draft,paid,paidDate,status:(draft.type==="Income"?undefined:paid?"Paid":draft.status==="Missed"?"Missed":(draft.plannedDate||draft.dueDate||draft.recurring)?"Upcoming":undefined) as Transaction["status"],date:paid?paidDate!:draft.date||draft.plannedDate||draft.dueDate||guidance.date,recurrenceStart:draft.recurring?(draft.recurrenceStart||draft.plannedDate||draft.dueDate||draft.date||guidance.date):undefined,recurrenceFrequency:draft.recurring?(draft.recurrenceFrequency||"Monthly"):undefined,recurrenceInterval:draft.recurring?Math.max(1,draft.recurrenceInterval||1):undefined,recurrenceEnd:draft.recurring?draft.recurrenceEnd:undefined};update(d=>({...d,transactions:[...d.transactions.filter(t=>t.id!==saved.id),saved.type==="Income"?{...saved,classification:undefined,paid:undefined,paidDate:undefined,status:undefined}:saved]}));setDraft(null);}}>
      <Field label="Description"><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field>
      <Field label="Type"><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value,category:e.target.value==="Income"?"Income":draft.type==="Income"?(data.categories[0]??"Other"):draft.category,classification:e.target.value==="Income"?"":["Savings","Investment"].includes(e.target.value)?"Savings":draft.type==="Income"?"":draft.classification,paid:e.target.value==="Income"?undefined:draft.paid,paidDate:e.target.value==="Income"?undefined:draft.paidDate,status:e.target.value==="Income"?undefined:draft.status})}>{["Income","Expense","Savings","Investment","Giving"].map(t=><option key={t}>{t}</option>)}</select></Field>
      {draft.type!=="Income"&&<Field label="Transaction classification"><select required disabled={draft.type==="Savings"||draft.type==="Investment"} value={isSavings(draft)?"Savings":draft.classification??""} onChange={e=>setDraft({...draft,classification:e.target.value as Classification})}><option value="">Choose Need, Want, or Savings</option>{["Need","Want","Savings"].map(c=><option key={c}>{c}</option>)}</select></Field>}
      {draft.type==="Income"?<Field label="Income source (optional)"><input placeholder="Salary, freelance, gift..." value={draft.category==="Income"?"":draft.category} onChange={e=>setDraft({...draft,category:e.target.value||"Income"})}/></Field>:<Field label="Category"><select required value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{[...new Set([...data.categories,draft.category])].map(c=><option key={c}>{c}</option>)}</select></Field>}
      <Field label="Amount"><input type="number" min="0.01" step="0.01" required value={draft.amount>0?draft.amount:""} placeholder="0.00" onInvalid={e=>e.currentTarget.setCustomValidity("Number is required.")} onInput={e=>e.currentTarget.setCustomValidity("")} onChange={e=>setDraft({...draft,amount:e.target.value===""?0:Number(e.target.value)})}/></Field>
      <div className="le-grid-three"><Field label="Transaction date"><input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value,recurrenceStart:draft.recurring?(draft.recurrenceStart||e.target.value):draft.recurrenceStart})}/></Field><Field label="Planned date"><input type="date" value={draft.plannedDate??""} onChange={e=>setDraft({...draft,plannedDate:e.target.value||undefined,status:e.target.value||draft.dueDate||draft.recurring?(draft.status??"Upcoming"):undefined,recurrenceStart:draft.recurring?(e.target.value||draft.recurrenceStart||draft.date):draft.recurrenceStart})}/></Field><Field label="Due date"><input type="date" value={draft.dueDate??""} onChange={e=>setDraft({...draft,dueDate:e.target.value||undefined,status:e.target.value||draft.plannedDate||draft.recurring?(draft.status??"Upcoming"):undefined,recurrenceStart:draft.recurring?(e.target.value||draft.recurrenceStart||draft.date):draft.recurrenceStart})}/></Field></div>
      <label className="le-check-row"><input type="checkbox" checked={Boolean(draft.recurring)} onChange={e=>setDraft({...draft,recurring:e.target.checked,recurrenceFrequency:e.target.checked?(draft.recurrenceFrequency||"Monthly"):undefined,recurrenceInterval:e.target.checked?(draft.recurrenceInterval||1):undefined,recurrenceStart:e.target.checked?(draft.recurrenceStart||draft.plannedDate||draft.dueDate||draft.date||guidance.date):undefined,recurrenceEnd:e.target.checked?draft.recurrenceEnd:undefined,status:e.target.checked&&draft.type!=="Income"?(draft.status??"Upcoming"):draft.status})}/><span>Recurring income/expense</span><small>{draft.recurring?recurrenceLabel(draft):"Tick this for salary, rent, subscriptions, and other repeated money movement."}</small></label>
      {draft.recurring&&<><div className="le-grid-three"><Field label="Frequency"><select value={draft.recurrenceFrequency||"Monthly"} onChange={e=>setDraft({...draft,recurrenceFrequency:e.target.value as RecurrenceFrequency})}>{["Weekly","Biweekly","Monthly","Quarterly","Yearly"].map(option=><option key={option}>{option}</option>)}</select></Field><Field label="Every"><input type="number" min="1" step="1" value={draft.recurrenceInterval||1} onChange={e=>setDraft({...draft,recurrenceInterval:Math.max(1,Number(e.target.value)||1)})}/></Field><Field label="Starts"><input type="date" required value={draft.recurrenceStart||draft.plannedDate||draft.dueDate||draft.date||guidance.date} onChange={e=>setDraft({...draft,recurrenceStart:e.target.value})}/></Field></div><Field label="Ends (optional)"><input type="date" value={draft.recurrenceEnd??""} onChange={e=>setDraft({...draft,recurrenceEnd:e.target.value||undefined})}/></Field></>}
      {draft.type!=="Income"&&<Field label="Scheduled status"><select value={scheduledStatus(draft,guidance.date)} onChange={e=>setDraft({...draft,status:e.target.value as ScheduledStatus,paid:e.target.value==="Paid",paidDate:e.target.value==="Paid"?(draft.paidDate||guidance.date):undefined,date:e.target.value==="Paid"?(draft.paidDate||guidance.date):(draft.plannedDate||draft.dueDate||draft.date)})}>{["Upcoming","Paid","Missed"].map(status=><option key={status}>{status}</option>)}</select></Field>}
      {draft.type!=="Income"&&<label className="le-check-row"><input type="checkbox" checked={Boolean(draft.paid)} onChange={e=>setDraft({...draft,paid:e.target.checked,status:e.target.checked?"Paid":"Upcoming",paidDate:e.target.checked?(draft.paidDate||guidance.date):undefined,date:e.target.checked?(draft.paidDate||guidance.date):(draft.plannedDate||draft.dueDate||draft.date)})}/><span>Paid off</span><small>{draft.paidDate||guidance.date}</small></label>}
      {draft.type!=="Income"&&draft.paid&&<Field label="Paid date"><input type="date" value={draft.paidDate||draft.date||guidance.date} onChange={e=>setDraft({...draft,paidDate:e.target.value,date:e.target.value})}/></Field>}
      <Field label="Record currency"><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}>{data.currencies.map(c=><option key={c.code}>{c.code}</option>)}</select></Field>
      <SaveButton>Save transaction</SaveButton>
    </form></Modal>}
    {budget&&<Modal title="Pay-cycle budget" close={()=>setBudget(null)}><form onSubmit={e=>{e.preventDefault();if(data.budgets.some(b=>b.id!==budget.id&&b.category===budget.category&&b.month===budget.month&&b.currency===budget.currency)){setError("A budget already exists for this category, cycle, and currency.");return;}const categoryLimit=Number(new FormData(e.currentTarget).get("categoryLimit")||0);update(d=>{const categories={...d.spendingLimits.categories};if(categoryLimit>0)categories[budget.category]=categoryLimit;else delete categories[budget.category];return {...d,budgets:[...d.budgets.filter(b=>b.id!==budget.id),budget],spendingLimits:{...d.spendingLimits,categories}};});setBudget(null);setError("");}}><Field label="Category"><select value={budget.category} onChange={e=>setBudget({...budget,category:e.target.value})}>{[...new Set([...data.categories,budget.category])].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Budget amount"><input type="number" required min="0.01" step="0.01" value={budget.amount>0?budget.amount:""} placeholder="0.00" onInvalid={e=>e.currentTarget.setCustomValidity("Number is required.")} onInput={e=>e.currentTarget.setCustomValidity("")} onChange={e=>setBudget({...budget,amount:e.target.value===""?0:Number(e.target.value)})}/></Field><Field label="Custom category spending limit"><input name="categoryLimit" type="number" min="0" step="0.01" defaultValue={data.spendingLimits.categories[budget.category]>0?data.spendingLimits.categories[budget.category]:""} placeholder="Use budget amount" /></Field><Field label="Cycle start month"><input type="month" required value={budget.month} onChange={e=>setBudget({...budget,month:e.target.value})}/></Field>{error&&<p role="alert">{error}</p>}<SaveButton>Save budget</SaveButton></form></Modal>}
    {currencyOpen&&<Modal title="Add Custom Currency" close={()=>setCurrencyOpen(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const code=String(f.get("code")).trim().toUpperCase();update(d=>({...d,currency:code,currencies:[...d.currencies.filter(c=>c.code!==code),{code,name:String(f.get("name")),symbol:String(f.get("symbol"))}]}));setCurrencyOpen(false);}}><Field label="Currency code"><input name="code" required/></Field><Field label="Currency name"><input name="name" required/></Field><Field label="Currency symbol"><input name="symbol" required/></Field><SaveButton>Save currency</SaveButton></form></Modal>}
  </>;
}

export function BudgetWorkspace() {
  return <FinanceWorkspace budgetModule />;
}
