"use client";
import { useState, type CSSProperties } from "react";
import { BudgetBreakdown } from "./budget-breakdown";
import { allocationStatus } from "@/lib/allocation-status";
import { BrainCircuit, CalendarRange, Gauge, Plus, WalletCards } from "lucide-react";
import { budgetGuidanceSummary, financialTotals, budgetAllocation, classifications, isSavings, type Classification } from "@/lib/refinements";
import { useLife, uid, today, type LifeData } from "@/lib/life-store";
import { Button, Card, Empty, Field, Heading, Metric, Modal, RecordActions, Tabs, Progress } from "./workspace-ui";
import { CategoryManager, RecordManager } from "./record-manager";

const colors: Record<string,string> = { Income:"#3f7ea8", Expense:"#bd5364", Savings:"#5f9369", Remaining:"#8e7ac6", Investment:"#c69a42", Giving:"#b5737a" };
const categoryPalette: Record<string,string> = {
  Housing:"#4f7fa4", Utilities:"#8e7ac6", Food:"#c75469", Transport:"#d39a3f", Entertainment:"#9d7bc7",
  Savings:"#5f9369", Investments:"#4d8f78", Health:"#d47983", Giving:"#b5737a"
};
const chartColors = ["#c75469", "#d39a3f", "#5f9369", "#8e7ac6", "#4f7fa4", "#d47983", "#4d8f78", "#b5737a"];
type Transaction = LifeData["transactions"][number];
type Budget = LifeData["budgets"][number];
function BudgetGuidancePanel({ guidance, money }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string }) {
  const healthTone = guidance.health === "On Track" || guidance.health === "Ahead of Goal" ? "#5f9369" : guidance.health === "Slightly Above Plan" ? "#c69a42" : "#bd5364";
  const aiInsight = guidance.monthlyBudget <= 0 ? guidance.insight : guidance.todayRemaining >= 0 ? `You can spend ${money(guidance.todayRemaining)} more today and remain within your weekly plan.` : `Today is ${money(Math.abs(guidance.todayRemaining))} above target. Tomorrow's suggested spend is ${money(guidance.tomorrowSuggested)}.`;
  return <Card className="le-budget-guidance"><div className="le-row"><div><p className="le-eyebrow">Budget guidance</p><h2>One monthly budget, translated into today.</h2></div><span className="le-budget-health" style={{ color: healthTone }}>{guidance.health}</span></div>
    <div className="le-budget-guidance-stack">{[
      ["Monthly Budget", guidance.monthlyBudget, `${money(Math.max(0, guidance.monthlyRemaining))} remaining`],
      ["This Week", Math.max(0, guidance.weekRemaining), `${money(guidance.weeklyBudget)} weekly guide`],
      ["Today", Math.max(0, guidance.todayRemaining), `${money(guidance.dailyTarget)} recommended spend`],
    ].map(([label,value,detail])=><div key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong><small>{detail}</small></div>)}</div>
    <div className="le-budget-feedback"><div><p className="le-eyebrow">Spending feedback</p><strong>{money(guidance.todaySpent)} spent today</strong><p>{guidance.todayRemaining >= 0 ? `${money(guidance.todayRemaining)} available today.` : `${money(Math.abs(guidance.todayRemaining))} above today's guide. Tomorrow adjusts automatically.`}</p></div><div><p className="le-eyebrow">AI insight</p><p>{aiInsight}</p>{guidance.projectedMonthEnd > 0 && <small>At this pace, you could finish the month with about {money(guidance.projectedMonthEnd)} remaining.</small>}</div></div>
    {(guidance.weekSavings > 0 || guidance.goalProgress.length > 0) && <div className="le-budget-goals"><p className="le-eyebrow">Connected to your future goals</p><div className="le-inline"><span>This week you saved {money(guidance.weekSavings)}.</span>{guidance.goalProgress.map(goal=><span key={goal.title}>{goal.title}: +{goal.boost.toFixed(1)}%</span>)}</div></div>}
    <Progress value={guidance.monthlyBudget>0?guidance.monthlySpent/guidance.monthlyBudget*100:0} />
  </Card>;
}
function BudgetSummaryView({ guidance, money }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string }) {
  return <div className="le-finance-premium"><BudgetGuidancePanel guidance={guidance} money={money}/><div className="le-grid-three mt-6"><Card className="le-budget-orb-card"><p className="le-eyebrow">Monthly rhythm</p><div className="le-budget-donut" style={{"--budget-used":`${Math.min(100,Math.max(0,guidance.monthlyBudget?guidance.monthlySpent/guidance.monthlyBudget*100:0))}%`} as CSSProperties}><span>{Math.round(guidance.monthlyBudget?guidance.monthlySpent/guidance.monthlyBudget*100:0)}%</span></div><h3>Budget used</h3><p className="le-muted">{money(Math.max(0,guidance.monthlyRemaining))} breathing room remains.</p></Card><Card className="le-budget-orb-card"><p className="le-eyebrow">Today & this week</p><Gauge size={24}/><h3>{money(Math.max(0,guidance.todayRemaining))} today</h3><p className="le-muted">{money(Math.max(0,guidance.weekRemaining))} left in this week's envelope.</p><Progress value={guidance.weeklyBudget?guidance.weeklySpent/guidance.weeklyBudget*100:0}/></Card><Card className="le-budget-orb-card"><p className="le-eyebrow">Spending velocity</p><WalletCards size={24}/><h3>{Math.round(guidance.spendingVelocity)}%</h3><p className="le-muted">{guidance.spendingVelocity<=100?"You are moving within the monthly pace.":"Spending is moving faster than the month."}</p><Progress value={guidance.spendingVelocity}/></Card></div></div>;
}
function EnvelopesView({ guidance, money, selectedWeekStart, onSelectWeek }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string; selectedWeekStart: string; onSelectWeek: (weekStart: string) => void }) {
  const { data, update } = useLife();
  const [planning,setPlanning]=useState(false);
  const [calendar,setCalendar]=useState(false);
  const [draft,setDraft]=useState<Record<string,number>>({});
  const [calc,setCalc]=useState(`${Math.round(guidance.monthlyBudget)} / ${guidance.weekEnvelopes.length || 1}`);
  const calcResult=(()=>{try{const clean=calc.replace(/÷/g,"/").replace(/x/gi,"*").replace(/[^0-9+\-*/(). ]/g,"");const value=Function(`"use strict";return (${clean||0})`)();return Number.isFinite(value)?Number(value):0;}catch{return 0;}})();
  const openPlanner=()=>{setDraft(Object.fromEntries(guidance.weekEnvelopes.map(w=>[w.start,w.budget])));setPlanning(true);};
  const split=()=>setDraft(Object.fromEntries(guidance.weekEnvelopes.map(w=>[w.start,guidance.weekEnvelopes.length?guidance.monthlyBudget/guidance.weekEnvelopes.length:0])));
  const save=()=>{update(d=>({...d,weeklyBudgetPlans:[...d.weeklyBudgetPlans.filter(p=>!(p.currency===guidance.currency&&p.month===guidance.month)),...guidance.weekEnvelopes.map(w=>({id:d.weeklyBudgetPlans.find(p=>p.currency===guidance.currency&&p.month===guidance.month&&p.weekStart===w.start)?.id??uid(),month:guidance.month,weekStart:w.start,weekEnd:w.end,currency:guidance.currency,amount:Number(draft[w.start]??w.budget)}))]}));setPlanning(false);};
  return <div className="le-grid-main"><Card className="le-envelope-card"><div className="le-row"><div><p className="le-eyebrow">Weekly envelopes</p><h2>Monthly money, divided into calm weekly lanes.</h2></div><div className="le-inline"><Button secondary onClick={()=>setCalendar(!calendar)}><CalendarRange size={16}/>Calendar view</Button><Button onClick={openPlanner}>Envelope planning</Button></div></div>{calendar&&<div className="le-month-calendar"><h3>{new Date(`${guidance.month}-15T12:00:00`).toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h3>{guidance.weekEnvelopes.map(week=><button key={week.start} type="button" className={selectedWeekStart===week.start?"is-selected":""} onClick={()=>onSelectWeek(week.start)}><strong>{week.label}</strong><span>{week.start.slice(5)} to {week.end.slice(5)}</span></button>)}</div>}<div className="le-envelope-grid">{guidance.weekEnvelopes.map(week=>{const over=Math.max(0,-week.remaining);return <button type="button" key={week.label} onClick={()=>onSelectWeek(week.start)} className={`${week.start<=guidance.date&&week.end>=guidance.date?"is-current":""} ${selectedWeekStart===week.start?"is-selected":""}`}><span>{week.label}</span><h3>{money(Math.max(0,week.remaining))}</h3><p>{week.start.slice(5)} to {week.end.slice(5)}</p><small>{money(week.budget)} guide · {money(week.spent)} used{week.scheduled>0?` · ${money(week.scheduled)} scheduled`: ""}</small><Progress value={week.budget?week.spent/week.budget*100:0}/>{over>0&&<em>{money(over)} above this week. Daily guidance adjusts forward.</em>}</button>;})}</div></Card>{planning&&<Card className="le-envelope-planner"><p className="le-eyebrow">Envelope planning panel</p><h2>Split this month your way.</h2><dl className="le-record-details"><div><dt>Monthly Budget</dt><dd>{money(guidance.monthlyBudget)}</dd></div><div><dt>Available</dt><dd>{money(guidance.monthlyBudget)}</dd></div><div><dt>Number of weeks</dt><dd>{guidance.weekEnvelopes.length}</dd></div></dl><div className="le-mini-calculator"><Field label="Calculator"><input value={calc} onChange={e=>setCalc(e.target.value)} /></Field><strong>= {money(calcResult)}</strong></div><div className="le-inline"><Button secondary onClick={split}>Split Budget Across Weeks</Button><Button onClick={save} className="le-compact-action">Save split</Button></div><div className="le-envelope-edit-list">{guidance.weekEnvelopes.map(week=><Field key={week.start} label={`${week.label} · ${week.start.slice(5)} to ${week.end.slice(5)}`}><input type="number" min="0" step="0.01" value={draft[week.start]??week.budget} onChange={e=>setDraft({...draft,[week.start]:Number(e.target.value)})}/></Field>)}</div></Card>}</div>;
}
function DailyView({ guidance, money, selectedWeek }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string; selectedWeek: ReturnType<typeof budgetGuidanceSummary>["weekEnvelopes"][number] }) {
  const { data, update } = useLife();
  const [plan,setPlan]=useState<LifeData["dailyBudgetPlans"][number]|null>(null);
  const plans=data.dailyBudgetPlans.filter(p=>p.currency===data.currency&&p.date===guidance.date);
  const addPlan=()=>setPlan({id:uid(),date:guidance.date,category:"",amount:0,currency:data.currency,note:""});
  return <><Card className="le-daily-budget"><div className="le-row"><div><p className="le-eyebrow">Daily guidance</p><h2>What feels safe to spend today.</h2><p className="le-muted">{selectedWeek.label}: {money(selectedWeek.budget)} week budget · {money(selectedWeek.recommendedDaily)} recommended per day</p></div><Button onClick={addPlan}><Plus size={16}/>Plan spend</Button></div><div className="le-daily-budget-grid">{[["Available This Week",Math.max(0,selectedWeek.remaining)],["Recommended Per Day",selectedWeek.recommendedDaily],["Planned Today",guidance.plannedToday],["Spent Today",guidance.todaySpent]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div><p className="le-muted mt-5">{guidance.todayRemaining>=0?`You are currently ${money(guidance.todayRemaining)} below your daily recommendation.`:`You are ${money(Math.abs(guidance.todayRemaining))} above today's guide. The rest of the week adjusts forward.`}</p>{plans.length>0&&<div className="le-budget-category-list">{plans.map(p=><div key={p.id}><div className="le-row"><span>{p.note||p.category||"Planned item"}</span><small>{money(p.amount)}{p.category?` · ${p.category}`:""}</small></div><div className="le-inline"><button type="button" className="le-icon" aria-label={`Edit ${p.note||"planned spend"}`} onClick={()=>setPlan(p)}>Edit</button><button type="button" className="le-icon" aria-label={`Remove ${p.note||"planned spend"}`} onClick={()=>update(d=>({...d,dailyBudgetPlans:d.dailyBudgetPlans.filter(x=>x.id!==p.id)}))}>×</button></div></div>)}</div>}</Card>{plan&&<Modal title="Plan today's spending" close={()=>setPlan(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,dailyBudgetPlans:[...d.dailyBudgetPlans.filter(p=>p.id!==plan.id),plan]}));setPlan(null);}}><Field label="Item"><input required value={plan.note} onChange={e=>setPlan({...plan,note:e.target.value})} placeholder="Groceries, transport, lunch..." /></Field><Field label="Category (optional)"><select value={plan.category} onChange={e=>setPlan({...plan,category:e.target.value})}><option value="">Uncategorized</option>{data.categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Planned amount"><input type="number" min="0.01" step="0.01" required value={plan.amount} onChange={e=>setPlan({...plan,amount:Number(e.target.value)})}/></Field><Button type="submit" className="le-compact-save">Save planned spend</Button></form></Modal>}</>;
}
function CoachView({ guidance, money }: { guidance: ReturnType<typeof budgetGuidanceSummary>; money: (value: number) => string }) {
  const [question,setQuestion]=useState("");
  const answer=question.trim()?`Based on your monthly budget, I would keep today near ${money(Math.max(0,guidance.todayRemaining))} and protect ${money(Math.max(0,guidance.weekRemaining))} for the rest of this week. This is mock coaching for now, using your current budget data.`:"Ask about today, this week, a purchase, or how to stay on track.";
  return <Card className="le-coach-card"><div className="le-row"><div><p className="le-eyebrow">AI money coach</p><h2>Encouraging guidance, never judgment.</h2></div><BrainCircuit size={24}/></div><Field label="Ask a budget question"><textarea rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Can I afford dinner out tonight?" /></Field><div className="le-coach-answer"><strong>Coach</strong><p>{answer}</p></div></Card>;
}
export function FinanceWorkspace({ budgetModule = false }: { budgetModule?: boolean }) {
  const { data, update } = useLife(); const [tab,setTab]=useState(budgetModule?"Budget Summary":"Overview"); const [month,setMonth]=useState(today().slice(0,7)); const [selectedWeekStart,setSelectedWeekStart]=useState(""); const [draft,setDraft]=useState<Transaction|null>(null); const [budget,setBudget]=useState<Budget|null>(null); const [currencyOpen,setCurrencyOpen]=useState(false); const [allocation,setAllocation]=useState(data.allocation); const [error,setError]=useState("");
  const currency = data.currencies.find(c => c.code === data.currency) ?? { code: data.currency, symbol: data.currency };
  const money = (v:number) => `${currency.symbol} ${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const entries = data.transactions.filter(t => t.currency === data.currency && t.date.startsWith(month)); const budgets = data.budgets.filter(b => b.currency === data.currency && b.month === month);
  const {income,expenses,savings}=financialTotals(entries);
  const activeDate=month===today().slice(0,7)?today():`${month}-01`;
  const guidance=budgetGuidanceSummary(data,activeDate,data.currency);
  const selectedWeek=guidance.weekEnvelopes.find(week=>week.start===selectedWeekStart) ?? guidance.weekEnvelopes.find(week=>guidance.date>=week.start&&guidance.date<=week.end) ?? guidance.weekEnvelopes[0];
  const allocationBalance=budgetAllocation(data.transactions,data.budgets,month,data.currency);
  const allocationActual=classifications(entries);
  const newTransaction = (category?:string) => setDraft({id:uid(),title:"",type:"Expense",classification:"",amount:0,category:category??data.categories[0]??"Other",currency:data.currency,date:today().startsWith(month)?today():`${month}-01`});
  const breakdown = [...new Set(entries.filter(t=>t.type!=="Income").map(t=>isSavings(t) ? "Savings" : t.category))].map(name=>({name,value:entries.filter(t=>t.type!=="Income" && (isSavings(t) ? "Savings" : t.category)===name).reduce((s,t)=>s+t.amount,0)})).filter(x=>x.value>0);
  const categoryColor=(name:string,index:number)=>categoryPalette[name] ?? chartColors[index%chartColors.length];
  const total=breakdown.reduce((s,x)=>s+x.value,0); let angle=0;
  const pie=breakdown.map((x,i)=>{const from=angle;angle+=x.value/total*360;return `${categoryColor(x.name,i)} ${from}deg ${angle}deg`;}).join(",");
  const months=Array.from({length:6},(_,i)=>{const d=new Date(`${month}-15T12:00:00`);d.setMonth(d.getMonth()-5+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;});
  const series=months.map(m=>{const rows=data.transactions.filter(t=>t.currency===data.currency&&t.date.startsWith(m));const v=financialTotals(rows);const balance=budgetAllocation(data.transactions,data.budgets,m,data.currency);return {month:m,values:[v.income,v.expenses,v.savings,balance.available],classification:classifications(rows)};}); const maximum=Math.max(1,...series.flatMap(s=>s.values.map(Math.abs)));
  const financeTabs=["Overview","Transactions","Budget","Savings goals","Categories","Guidance"];
  const budgetTabs=["Budget Summary","Budget","Envelopes","Daily","Categories","Coach","Guidance"];
  return <><Heading section={budgetModule?"Budget system":"Financial wellbeing"} title={budgetModule?"Plan what this month becomes.":"See where your money goes."}><div className="le-inline"><select aria-label="Currency" value={data.currency} onChange={e=>e.target.value==="custom"?setCurrencyOpen(true):update(d=>({...d,currency:e.target.value}))}>{data.currencies.map(c=><option key={c.code} value={c.code}>{c.code} · {c.name}</option>)}<option value="custom">+ Add Custom Currency</option></select><input aria-label="Financial month" type="month" required value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}} /></div></Heading><div className="le-grid-four le-kpi-grid">{[["Income",income],["Expense",expenses],["Savings",savings],["Remaining",allocationBalance.available]].map(([name,value])=><Metric key={name} label={name==="Expense"?"Expenses":name==="Remaining"?"Available to allocate":String(name)} value={money(Number(value))} color={colors[String(name)]} />)}</div><div className="my-6"><Tabs items={budgetModule?budgetTabs:financeTabs} active={tab} onChange={setTab} /></div>
    {data.allocation.enabled&&<div className="mb-6" aria-live="polite">{(["needs","wants","savings"] as const).map(key=>{const label=key[0].toUpperCase()+key.slice(1);const actual=allocationActual[key==="needs"?"Need":key==="wants"?"Want":"Savings"];const status=allocationStatus(income,data.allocation[key],actual);return status.state==="within"||status.state==="no-income"?null:<p className="le-log" key={key} style={{color:status.state==="exceeded"?"#a83747":undefined}}>{status.state==="exceeded"?`${label}: ${money(-status.remaining)} above your ${data.allocation[key]}% allocation (${money(status.target)}).`:status.state==="reached"?`${label}: your ${data.allocation[key]}% allocation has been reached.`:`${label}: approaching your ${data.allocation[key]}% allocation. ${status.used.toFixed(0)}% used; ${money(status.remaining)} remaining.`}</p>;})}{allocationActual.Unclassified>0&&<p className="le-muted">Unclassified outgoings: {money(allocationActual.Unclassified)}. Allocation totals exclude these records.</p>}</div>}
    {tab==="Overview"&&<><BudgetGuidancePanel guidance={guidance} money={money}/><div className="le-grid-two mt-6"><Card><h2>Spending by category</h2>{!total?<Empty title="Add transactions to see your spending." />:<div className="le-pie-layout"><div className="le-pie" role="img" aria-label={`Spending distribution: ${breakdown.map(x=>`${x.name} ${money(x.value)}`).join(", ")}`} style={{background:`conic-gradient(${pie})`}}/><ul className="le-chart-legend">{breakdown.map((x,i)=><li key={x.name}><i style={{background:categoryColor(x.name,i)}}/><span>{x.name}</span><strong>{money(x.value)}</strong></li>)}</ul></div>}</Card><Card><h2>Financial health</h2><dl className="le-record-details">{[["Total income",money(income)],["Total expenses",money(expenses)],["Amount saved",money(savings)],["Savings rate",income?`${(savings/income*100).toFixed(1)}%`:"No income recorded"],["Reserved for budgets",money(allocationBalance.reserved)],["Spending outside budgets",money(allocationBalance.unbudgeted)],["Spending over budgets",money(allocationBalance.overspent)],["Available to allocate",money(allocationBalance.available)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Card></div><Card className="mt-6"><h2>Income, expenses, savings, and available funds</h2><div className="le-bar-chart" role="img" aria-label="Six-month income, expenses, savings and available-to-allocate comparison">{series.map(s=><div className="le-bar-month" key={s.month}><div className="le-bars le-signed-bars">{s.values.map((v,i)=><div className="le-bar-slot" key={i} title={`${["Income","Expenses","Savings","Available to allocate"][i]}: ${money(v)}`}><span style={{height:`${Math.abs(v)/maximum*48}%`,background:Object.values(colors)[i],bottom:v>=0?"50%":undefined,top:v<0?"50%":undefined}}/></div>)}</div><small>{s.month.slice(5)}</small></div>)}</div><ul className="le-chart-legend le-inline">{Object.entries(colors).slice(0,4).map(([name,color])=><li key={name}><i style={{background:color}}/>{name==="Remaining"?"Available to allocate":name}</li>)}</ul><details className="mt-5"><summary>View chart data</summary><div className="le-table-scroll"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Savings</th><th>Available to allocate</th></tr></thead><tbody>{series.map(s=><tr key={s.month}><th>{s.month}</th>{s.values.map((v,i)=><td key={i}>{money(v)}</td>)}</tr>)}</tbody></table></div></details></Card></>}
    {tab==="Budget Summary"&&<BudgetSummaryView guidance={guidance} money={money}/>}
    {tab==="Overview"&&<Card className="mt-6"><h2>Needs, wants, and savings over time</h2><p className="le-muted mt-3">Percentages of recorded outgoings in {data.currency}. Income is excluded. Unclassified records remain visible until you review them.</p><div className="le-table-scroll"><table><thead><tr><th>Month</th><th>Needs</th><th>Wants</th><th>Savings</th><th>Unclassified</th></tr></thead><tbody>{series.map(s=>{const total=Object.values(s.classification).reduce((a,b)=>a+b,0);return <tr key={s.month}><th>{s.month}</th>{Object.values(s.classification).map((v,i)=><td key={i}>{total?(v/total*100).toFixed(1)+"%":"—"}</td>)}</tr>;})}</tbody></table></div></Card>}
    {tab==="Transactions"&&<><div className="le-row mb-5"><h2>Income and outgoings</h2><Button onClick={()=>newTransaction()}><Plus size={16}/>Add transaction</Button></div>{!entries.length?<Empty title="No transactions this month." action="Add transaction" onClick={()=>newTransaction()}/>:<Card>{entries.map(t=><div key={t.id} className="le-row le-log"><div><strong>{t.title}</strong><p className="le-muted">{t.date} · {t.category} · {t.type}{t.type!=="Income"&&` · ${isSavings(t)?"Savings":t.classification||"Unclassified"}`}</p></div><div className="le-inline"><strong style={{color:colors[t.type]}}>{money(t.amount)}</strong><RecordActions name={t.title} edit={()=>setDraft(t)} remove={()=>update(d=>({...d,transactions:d.transactions.filter(x=>x.id!==t.id)}))}/></div></div>)}</Card>}</>}
    {tab==="Budget"&&<><BudgetGuidancePanel guidance={guidance} money={money}/><BudgetBreakdown key={`${month}:${data.currency}`} budgets={budgets} entries={entries} money={money} addBudget={()=>{setError("");setBudget({id:uid(),category:data.categories[0]??"Other",currency:data.currency,month,amount:0});}} editBudget={b=>{setError("");setBudget(b);}} deleteBudget={id=>update(d=>({...d,budgets:d.budgets.filter(b=>b.id!==id)}))} addSpending={newTransaction} editTransaction={setDraft} deleteTransaction={id=>update(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}))}/></>}
    {tab==="Envelopes"&&<EnvelopesView guidance={guidance} money={money} selectedWeekStart={selectedWeek?.start??""} onSelectWeek={setSelectedWeekStart}/>}
    {tab==="Daily"&&selectedWeek&&<DailyView guidance={guidance} money={money} selectedWeek={selectedWeek}/>}

    {tab==="Savings goals"&&<RecordManager collection="savingsGoals" title="Savings goals" singular="savings goal" fields={[{key:"title",label:"Goal name",required:true},{key:"target",label:"Target amount",type:"number",min:0.01,required:true},{key:"saved",label:"Amount saved",type:"number",min:0},{key:"currency",label:"Goal currency",type:"select",options:data.currencies.map(c=>c.code),initial:data.currency},{key:"due",label:"Target date",type:"date"}]}/>}
    {tab==="Categories"&&<CategoryManager categoryKey="categories" title="Budget categories"/>}
    {tab==="Coach"&&<CoachView guidance={guidance} money={money}/>}
    {tab==="Guidance"&&<Card><h2>Your allocation, your choice.</h2><label className="le-check-row"><input type="checkbox" checked={allocation.enabled} onChange={e=>{setAllocation({...allocation,enabled:e.target.checked});update(d=>({...d,allocation:{...d.allocation,enabled:e.target.checked}}));}}/>Show optional budget guidance</label>{allocation.enabled&&<form onSubmit={e=>{e.preventDefault();if(Math.abs(allocation.needs+allocation.wants+allocation.savings-100)>0.001){setError("Your allocation must total 100%.");return;}update(d=>({...d,allocation}));setError("Allocation saved.");}}><p className="le-muted mt-5">The 50 / 30 / 20 guideline is a starting point. Adjust it to your circumstances.</p><a href="https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/teach/activities/analyzing-budgets/" target="_blank" rel="noreferrer">About the CFPB budgeting guideline</a><div className="le-grid-three">{(["needs","wants","savings"] as const).map(key=><Field key={key} label={`${key[0].toUpperCase()+key.slice(1)} (%)`}><input type="number" min="0" max="100" required value={allocation[key]} onChange={e=>setAllocation({...allocation,[key]:Number(e.target.value)})}/><small>Target: {money(income*allocation[key]/100)}</small><small>Actual: {money(allocationActual[key==="needs"?"Need":key==="wants"?"Want":"Savings"])}</small><Progress value={income*allocation[key]>0?allocationActual[key==="needs"?"Need":key==="wants"?"Want":"Savings"]/(income*allocation[key]/100)*100:0}/></Field>)}</div><div className="le-inline"><Button type="submit">Save allocation</Button><Button secondary onClick={()=>setAllocation({enabled:true,needs:50,wants:30,savings:20})}>50 / 30 / 20</Button></div>{error&&<p role="status" className="mt-4">{error}</p>}</form>}</Card>}
    {draft&&<Modal title={data.transactions.some(t=>t.id===draft.id)?"Edit transaction":"New transaction"} close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,transactions:[...d.transactions.filter(t=>t.id!==draft.id),draft.type==="Income"?{...draft,classification:undefined}:draft]}));setDraft(null);}}><Field label="Description"><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="Type"><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value,category:e.target.value==="Income"?"Income":draft.type==="Income"?(data.categories[0]??"Other"):draft.category,classification:e.target.value==="Income"?"":["Savings","Investment"].includes(e.target.value)?"Savings":draft.type==="Income"?"":draft.classification})}>{["Income","Expense","Savings","Investment","Giving"].map(t=><option key={t}>{t}</option>)}</select></Field>{draft.type!=="Income"&&<Field label="Transaction classification"><select required disabled={draft.type==="Savings"||draft.type==="Investment"} value={isSavings(draft)?"Savings":draft.classification??""} onChange={e=>setDraft({...draft,classification:e.target.value as Classification})}><option value="">Choose Need, Want, or Savings</option>{["Need","Want","Savings"].map(c=><option key={c}>{c}</option>)}</select></Field>}{draft.type==="Income"?<Field label="Income source (optional)"><input placeholder="Salary, freelance, gift..." value={draft.category==="Income"?"":draft.category} onChange={e=>setDraft({...draft,category:e.target.value||"Income"})}/></Field>:<Field label="Category"><select required value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{[...new Set([...data.categories,draft.category])].map(c=><option key={c}>{c}</option>)}</select></Field>}<Field label="Amount"><input type="number" min="0.01" step="0.01" required value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></Field><Field label="Date"><input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></Field><Field label="Record currency"><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}>{data.currencies.map(c=><option key={c.code}>{c.code}</option>)}</select></Field><Button type="submit">Save transaction</Button></form></Modal>}
    {budget&&<Modal title="Monthly budget" close={()=>setBudget(null)}><form onSubmit={e=>{e.preventDefault();if(data.budgets.some(b=>b.id!==budget.id&&b.category===budget.category&&b.month===budget.month&&b.currency===budget.currency)){setError("A budget already exists for this category, month, and currency.");return;}update(d=>({...d,budgets:[...d.budgets.filter(b=>b.id!==budget.id),budget]}));setBudget(null);setError("");}}><Field label="Category"><select value={budget.category} onChange={e=>setBudget({...budget,category:e.target.value})}>{[...new Set([...data.categories,budget.category])].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Budget amount"><input type="number" required min="0.01" step="0.01" value={budget.amount} onChange={e=>setBudget({...budget,amount:Number(e.target.value)})}/></Field><Field label="Month"><input type="month" required value={budget.month} onChange={e=>setBudget({...budget,month:e.target.value})}/></Field>{error&&<p role="alert">{error}</p>}<Button type="submit" className="le-compact-save">Save budget</Button></form></Modal>}
    {currencyOpen&&<Modal title="Add Custom Currency" close={()=>setCurrencyOpen(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const code=String(f.get("code")).trim().toUpperCase();update(d=>({...d,currency:code,currencies:[...d.currencies.filter(c=>c.code!==code),{code,name:String(f.get("name")),symbol:String(f.get("symbol"))}]}));setCurrencyOpen(false);}}><Field label="Currency code"><input name="code" required/></Field><Field label="Currency name"><input name="name" required/></Field><Field label="Currency symbol"><input name="symbol" required/></Field><Button type="submit">Save currency</Button></form></Modal>}
  </>;
}

export function BudgetWorkspace() {
  return <FinanceWorkspace budgetModule />;
}
