"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { useLife, uid, today, type Workout, type LifeData } from "@/lib/life-store";
import { FitnessProgress } from "./fitness-progress";
import { workoutTemplates, type Exercise } from "@/lib/life-domain";
import { Button, Card, Empty, Field, Heading, IconButton, Metric, Modal, RecordActions, Tabs } from "./workspace-ui";
import { CategoryManager, RecordManager } from "./record-manager";

const blankExercise = (): Exercise => ({ id:uid(),name:"",category:"Custom",sets:3,reps:10,weight:0,rest:60,seconds:0,notes:"" });
const volume = (exercises:Workout["exercises"]) => exercises.reduce((s,e)=>s+e.sets*e.reps*e.weight,0);
function ExerciseFields({ rows, change }: { rows:Workout["exercises"];change:(rows:Workout["exercises"])=>void }) {
  return <>{rows.map((ex,index)=><fieldset className="le-exercise" key={ex.id}><legend>Exercise {index+1}</legend><Field label="Exercise name"><input required value={ex.name} onChange={e=>change(rows.map(x=>x.id===ex.id?{...x,name:e.target.value}:x))}/></Field><div className="le-grid-three">{([['sets','Sets'],['reps','Reps'],['weight','Weight (kg)'],['seconds','Time (seconds)'],['rest','Rest (seconds)']] as const).map(([key,label])=><Field key={key} label={label}><input type="number" required min={key==="sets"?1:0} step={key==="weight"?"0.1":"1"} value={ex[key]??0} onChange={e=>change(rows.map(x=>x.id===ex.id?{...x,[key]:Number(e.target.value)}:x))}/></Field>)}</div><Field label="Exercise notes"><textarea value={ex.notes??""} onChange={e=>change(rows.map(x=>x.id===ex.id?{...x,notes:e.target.value}:x))}/></Field><IconButton title={`Remove ${ex.name||"exercise"}`} onClick={()=>change(rows.filter(x=>x.id!==ex.id))}><Trash2 size={16}/></IconButton></fieldset>)}</>;
}
export function FitnessWorkspace() {
  const { data,update }=useLife(); const [tab,setTab]=useState("Progress"); const [draft,setDraft]=useState<Workout|null>(null); const [exercise,setExercise]=useState<Exercise|null>(null); const [log,setLog]=useState<LifeData["workoutLogs"][number]|null>(null); const [archived,setArchived]=useState(false); const [month,setMonth]=useState(today().slice(0,7)); const [search,setSearch]=useState(""); const [removedExercise,setRemovedExercise]=useState<Workout["exercises"][number]|null>(null);
  function add() {setRemovedExercise(null);setDraft({id:uid(),name:"",category:data.workoutTypes[0]??"Custom",warmup:"",cooldown:"",notes:"",exercises:[],archived:false});}
  function useTemplate(name:string) {setDraft({id:uid(),name,category:name,warmup:"Walking or light cardio; gentle mobility drills",cooldown:"Gentle stretching or foam rolling",notes:"",archived:false,exercises:workoutTemplates[name].map(exName=>({...blankExercise(),...(data.exercises.find(ex=>ex.name===exName)??{}),id:uid(),name:exName}))});setRemovedExercise(null);}
  const logs=data.workoutLogs.filter(l=>l.date.startsWith(month)); const measures=data.measurements.slice().sort((a,b)=>a.date.localeCompare(b.date)); const weights=measures.filter(m=>m.weight>0); const maxWeight=Math.max(1,...weights.map(m=>m.weight)); const minWeight=Math.min(...weights.map(m=>m.weight));
  const records=Object.values(data.workoutLogs.reduce<Record<string,{name:string;weight:number;reps:number}>>((acc,l)=>{for(const ex of l.exercises??[])if(ex.weight>0&&(!acc[ex.name]||ex.weight>acc[ex.name].weight))acc[ex.name]={name:ex.name,weight:ex.weight,reps:ex.reps};return acc;},{}));
  return <><Heading section="Movement with purpose" title="Build strength. Notice progress."><Button onClick={add}><Plus size={16}/>Create workout plan</Button></Heading><Tabs items={["Progress","Workouts","Exercise Library","Plans","Settings"]} active={tab} onChange={setTab}/>
    {tab==="Workouts"&&<><label className="le-inline my-5"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Show archived</label>{!data.workouts.filter(w=>Boolean(w.archived)===archived).length?<Empty title="Create your first workout plan." action="Build a workout" onClick={add}/>:<div className="le-grid-two">{data.workouts.filter(w=>Boolean(w.archived)===archived).map(w=><Card key={w.id}><p className="le-eyebrow">{w.category}</p><h2>{w.name}</h2><RecordActions name={w.name} edit={()=>{setDraft(w);setRemovedExercise(null);}} remove={()=>update(d=>({...d,workouts:d.workouts.filter(x=>x.id!==w.id)}))} archive={()=>update(d=>({...d,workouts:d.workouts.map(x=>x.id===w.id?{...x,archived:!x.archived}:x)}))} archived={w.archived}/><h3 className="mt-5">Warm up</h3><p className="le-muted">{w.warmup||"Not added"}</p><h3 className="mt-5">Main workout</h3>{w.exercises.map(ex=><div className="le-log" key={ex.id}><strong>{ex.name}</strong><p className="le-muted">{ex.sets} sets · {ex.reps} reps · {ex.weight} kg · {ex.seconds??0}s · {ex.rest}s rest</p>{ex.notes&&<p>{ex.notes}</p>}</div>)}<h3 className="mt-5">Cool down</h3><p className="le-muted">{w.cooldown||"Not added"}</p>{w.notes&&<p className="mt-3">{w.notes}</p>}<Button secondary onClick={()=>setLog({id:uid(),name:w.name,date:today(),minutes:0,volume:volume(w.exercises),exercises:w.exercises.map(ex=>({...ex})),notes:""})}>Log workout</Button></Card>)}</div>}</>}
    {tab==="Plans"&&<><p className="le-muted my-5">Choose a starting point, then adjust every exercise, set, and duration.</p><div className="le-grid-three">{Object.entries(workoutTemplates).map(([name,exercises])=><Card key={name}><h2>{name}</h2><p className="le-muted my-5">{exercises.join(" · ")}</p><Button secondary onClick={()=>useTemplate(name)}>Use {name} template</Button></Card>)}</div><a className="mt-5" href="https://www.acefitness.org/resources/everyone/exercise-library/" target="_blank" rel="noreferrer">Explore exercise technique with ACE</a></>}
    {tab==="Exercise Library"&&<><div className="le-row my-5"><input aria-label="Search exercises" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search exercises"/><Button onClick={()=>setExercise(blankExercise())}><Plus size={16}/>Create custom exercise</Button></div><div className="le-grid-three">{data.exercises.filter(ex=>`${ex.name} ${ex.category}`.toLowerCase().includes(search.toLowerCase())).map(ex=><Card key={ex.id}><p className="le-eyebrow">{ex.category}</p><h3>{ex.name}</h3><p className="le-muted mt-3">{ex.sets} sets · {ex.reps} reps · {ex.weight} kg · {ex.seconds}s</p><p>{ex.notes}</p><RecordActions name={ex.name} edit={()=>setExercise(ex)} remove={()=>update(d=>({...d,exercises:d.exercises.filter(x=>x.id!==ex.id)}))}/></Card>)}</div></>}
    {tab==="Settings"&&<div className="mt-6"><Card><h2>Your fitness goal</h2><Field label="Goal weight (kg)"><input type="number" min="0.1" step="0.1" value={data.goalWeight??""} onChange={e=>update(d=>({...d,goalWeight:e.target.value&&Number(e.target.value)>0?Number(e.target.value):null}))}/></Field></Card><div className="le-grid-two mt-6"><CategoryManager categoryKey="workoutTypes" title="Workout categories"/><CategoryManager categoryKey="exerciseCategories" title="Exercise categories"/></div></div>}
    {tab==="Progress"&&<FitnessProgress/>}
    {tab==="Workouts"&&<Card className="mt-6"><h2>Workout history</h2>{!data.workoutLogs.length?<Empty title="Your first workout is ahead of you."/>:data.workoutLogs.slice().reverse().map(l=><div className="le-row le-log" key={l.id}><div><h3>{l.name}</h3><p className="le-muted">{l.date} · {l.minutes} minutes · {l.volume} kg volume</p><p>{l.notes}</p></div><RecordActions name={`${l.name} log`} edit={()=>setLog(l)} remove={()=>update(d=>({...d,workoutLogs:d.workoutLogs.filter(x=>x.id!==l.id)}))}/></div>)}</Card>}
    {draft&&<Modal title="Workout builder" close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,workouts:[...d.workouts.filter(w=>w.id!==draft.id),draft]}));setDraft(null);}}><Field label="Workout name"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Workout category"><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{[...new Set([...data.workoutTypes,...Object.keys(workoutTemplates),draft.category])].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Warm up"><textarea value={draft.warmup} onChange={e=>setDraft({...draft,warmup:e.target.value})}/></Field><h3>Main workout</h3><Field label="Add from exercise library"><select value="" onChange={e=>{const ex=data.exercises.find(x=>x.id===e.target.value);if(ex)setDraft({...draft,exercises:[...draft.exercises,{...ex,id:uid()}]});}}><option value="">Choose an exercise</option>{data.exercises.map(ex=><option value={ex.id} key={ex.id}>{ex.name}</option>)}</select></Field><ExerciseFields rows={draft.exercises} change={rows=>{const removed=draft.exercises.find(x=>!rows.some(y=>y.id===x.id));if(removed)setRemovedExercise(removed);setDraft({...draft,exercises:rows});}}/>{removedExercise&&<Button secondary onClick={()=>{setDraft({...draft,exercises:[...draft.exercises,removedExercise]});setRemovedExercise(null);}}>Undo remove exercise</Button>}<Button secondary onClick={()=>setDraft({...draft,exercises:[...draft.exercises,blankExercise()]})}><Plus size={16}/>Add custom exercise</Button><Field label="Cool down"><textarea value={draft.cooldown??""} onChange={e=>setDraft({...draft,cooldown:e.target.value})}/></Field><Field label="Workout notes"><textarea value={draft.notes??""} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><Button type="submit">Save workout</Button></form></Modal>}
    {exercise&&<Modal title="Exercise library" close={()=>setExercise(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,exercises:[...d.exercises.filter(x=>x.id!==exercise.id),exercise]}));setExercise(null);}}><Field label="Exercise category"><select value={exercise.category} onChange={e=>setExercise({...exercise,category:e.target.value})}>{[...new Set([...data.exerciseCategories,exercise.category])].map(c=><option key={c}>{c}</option>)}</select></Field><ExerciseFields rows={[exercise]} change={rows=>{if(rows[0])setExercise({...exercise,...rows[0]});else setExercise(null);}}/><Button type="submit">Save exercise</Button></form></Modal>}
    {log&&<Modal title="Record your workout" close={()=>setLog(null)}><form onSubmit={e=>{e.preventDefault();const saved={...log,volume:log.exercises?volume(log.exercises):log.volume};update(d=>({...d,workoutLogs:[...d.workoutLogs.filter(x=>x.id!==log.id),saved]}));setLog(null);setTab("Workouts");}}><Field label="Workout name"><input required value={log.name} onChange={e=>setLog({...log,name:e.target.value})}/></Field><Field label="Date"><input type="date" required value={log.date} onChange={e=>setLog({...log,date:e.target.value})}/></Field><Field label="Duration (minutes)"><input type="number" min="1" required value={log.minutes} onChange={e=>setLog({...log,minutes:Number(e.target.value)})}/></Field><ExerciseFields rows={log.exercises??[]} change={rows=>setLog({...log,exercises:rows})}/><Field label="Session notes"><textarea value={log.notes??""} onChange={e=>setLog({...log,notes:e.target.value})}/></Field><Button type="submit">Save workout log</Button></form></Modal>}
  </>;
}
