"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLife,today,uid,type LifeData } from "@/lib/life-store";
import { Button,Card,Empty,Field,Metric,Modal,RecordActions } from "./workspace-ui";
import { RecordManager } from "./record-manager";
import { ImageUpload,MediaImage } from "./workspace-media";

export function Trend({title,points,unit,onAdd}:{title:string;points:{date:string;value:number}[];unit:string;onAdd?:()=>void}) {
  const [selection,setSelection]=useState<string | null>(null);
  const selected=points.find((p,i)=>`${p.date}:${p.value}:${i}`===selection);
  const min=Math.min(...points.map(p=>p.value));const max=Math.max(...points.map(p=>p.value));
  const coords=points.map((p,i)=>({x:30+i/Math.max(1,points.length-1)*340,y:130-(p.value-min)/Math.max(1,max-min)*100}));
  return <Card><div className="le-row"><h2>{title}</h2>{onAdd&&<button type="button" className="le-icon" title="Add progress entry" aria-label={`Add entry to ${title}`} onClick={onAdd}><Plus size={18}/></button>}</div>{!points.length?<Empty title="Add an entry to begin your trend." action={onAdd?"Add progress entry":undefined} onClick={onAdd}/>:<><div className="le-interactive-trend"><svg viewBox="0 0 400 175" role="img" aria-label={`${title}: ${points.map(p=>`${p.date}: ${p.value} ${unit}`).join(", ")}`}><line x1="25" y1="140" x2="380" y2="140" stroke="currentColor" opacity=".2"/><polyline fill="none" stroke="currentColor" strokeWidth="2.5" points={coords.map(p=>`${p.x},${p.y}`).join(" ")}/>{coords.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="4" fill="currentColor"/>)}<text x="25" y="162" fontSize="10" fill="currentColor">{points[0].date}</text><text x="380" y="162" fontSize="10" textAnchor="end" fill="currentColor">{points.at(-1)?.date}</text></svg>{coords.map((p,i)=>{const key=`${points[i].date}:${points[i].value}:${i}`;return <button type="button" className="le-trend-point" key={key} style={{left:`${p.x/4}%`,top:`${p.y/1.75}%`}} aria-label={`${title}, ${points[i].date}: ${points[i].value} ${unit}`} aria-pressed={selection===key} onClick={()=>setSelection(key)}/>;})}</div><p className="le-muted" role="status">{selected?`${selected.date}: ${selected.value} ${unit}`:`${points.at(-1)?.value} ${unit} latest · ${min}–${max} ${unit} range`}</p></>}</Card>;
}
export function FitnessProgress() {
  const {data,update}=useLife();const [createRequest,setCreateRequest]=useState(0);const addEntry=()=>setCreateRequest(n=>n+1);const [month,setMonth]=useState(today().slice(0,7));const [measure,setMeasure]=useState<"waist"|"chest"|"hips">("waist");const [first,setFirst]=useState("");const [second,setSecond]=useState("");const [photo,setPhoto]=useState<LifeData["fitnessPhotos"][number]|null>(null);const [uploading,setUploading]=useState(false);const [selectedDay,setSelectedDay]=useState("");
  const entries=data.measurements.slice().sort((a,b)=>a.date.localeCompare(b.date));const weights=entries.filter(e=>e.weight>0);const start=weights[0]?.weight;const current=weights.at(-1)?.weight;const change=current!==undefined&&start!==undefined?current-start:undefined;const from=entries.find(e=>e.id===first)??entries[0];const to=entries.find(e=>e.id===second)??entries.at(-1);
  const logs=data.workoutLogs.filter(l=>l.date.startsWith(month));const days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();const offset=(new Date(`${month}-01T12:00:00`).getDay()+6)%7;
  const records=Object.values(data.workoutLogs.reduce<Record<string,{name:string;weight:number;reps:number}>>((acc,l)=>{for(const ex of l.exercises??[])if(ex.weight>0&&(!acc[ex.name]||ex.weight>acc[ex.name].weight))acc[ex.name]={name:ex.name,weight:ex.weight,reps:ex.reps};return acc;},{}));
  const addPhoto=()=>setPhoto({id:uid(),date:today(),title:"",image:"",notes:""});
  return <><div className="le-grid-four mt-6"><Metric label="Current weight" value={current!==undefined?`${current} kg`:"—"}/><Metric label="Goal weight" value={data.goalWeight?`${data.goalWeight} kg`:"Not set"}/><Metric label="Starting weight" value={start!==undefined?`${start} kg`:"—"}/><Metric label="Weight change" value={change!==undefined?`${change>0?"+":""}${change.toFixed(1)} kg`:"—"}/></div><div className="le-grid-two mt-6"><Trend onAdd={addEntry} title="Weight trend" points={weights.map(e=>({date:e.date,value:e.weight}))} unit="kg"/><div><Field label="Measurement trend"><select value={measure} onChange={e=>setMeasure(e.target.value as typeof measure)}><option value="waist">Waist</option><option value="chest">Chest</option><option value="hips">Hips</option></select></Field><Trend key={measure} onAdd={addEntry} title={`${measure[0].toUpperCase()+measure.slice(1)} measurements`} points={entries.filter(e=>e[measure]>0).map(e=>({date:e.date,value:e[measure]}))} unit="cm"/></div></div>
    <div className="le-row my-6"><h2>Monthly fitness summary</h2><input type="month" aria-label="Fitness month" required value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelectedDay("");}}}/></div><div className="le-grid-four"><Metric label="Workouts" value={logs.length}/><Metric label="Active days" value={new Set(logs.map(l=>l.date)).size}/><Metric label="Minutes" value={logs.reduce((s,l)=>s+l.minutes,0)}/><Metric label="Volume (kg)" value={logs.reduce((s,l)=>s+l.volume,0).toLocaleString()}/></div><div className="le-grid-two mt-6"><Card><h2>Consistency calendar</h2><div className="le-consistency">{["M","T","W","T","F","S","S"].map((d,i)=><small key={i}>{d}</small>)}{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;const count=logs.filter(l=>l.date===date).length;return <button key={date} aria-label={`${date}: ${count} workouts`} aria-pressed={selectedDay===date} className={count?"is-active":""} onClick={()=>setSelectedDay(date)}>{i+1}{count>0&&<small>{count}</small>}</button>;})}</div>{selectedDay&&<p className="le-muted mt-4">{selectedDay}: {data.workoutLogs.filter(l=>l.date===selectedDay).map(l=>l.name).join(", ")||"No workouts recorded"}</p>}</Card><Card><h2>Progress highlights</h2><p className="mt-5">{new Set(logs.map(l=>l.date)).size} active days this month.</p><p>{data.measurements.length} progress entries recorded.</p>{current!==undefined&&data.goalWeight&&<p>{Math.abs(current-data.goalWeight).toFixed(1)} kg from your goal weight.</p>}<h3 className="mt-5">Personal records</h3>{records.length?records.map(r=><div className="le-row le-log" key={r.name}><span>{r.name}</span><strong>{r.weight} kg × {r.reps}</strong></div>):<p className="le-muted mt-3">Personal records appear after you log weighted exercises.</p>}</Card></div>
    <RecordManager createRequest={createRequest} collection="measurements" archive={false} title="Progress entries" singular="progress entry" fields={[{key:"date",label:"Progress date",type:"date",initial:today(),required:true},{key:"weight",label:"Body weight (kg)",type:"number",min:0},{key:"waist",label:"Waist (cm)",type:"number",min:0},{key:"chest",label:"Chest (cm)",type:"number",min:0},{key:"hips",label:"Hips (cm)",type:"number",min:0},{key:"notes",label:"Notes",type:"textarea"}]}/>
    {entries.length>1&&<Card className="mt-6"><h2>Compare your progress</h2><div className="le-grid-two">{[["Compare from",from?.id??"",setFirst],["Compare to",to?.id??"",setSecond]].map(([label,value,set])=><Field key={String(label)} label={String(label)}><select value={String(value)} onChange={e=>(set as (v:string)=>void)(e.target.value)}>{entries.map((e,i)=><option key={e.id} value={e.id}>{e.date} · Entry {i+1}</option>)}</select></Field>)}</div><div className="le-table-scroll"><table><thead><tr><th>Measurement</th><th>From</th><th>To</th><th>Change</th></tr></thead><tbody>{(["weight","waist","chest","hips"] as const).map(key=><tr key={key}><th>{key} ({key==="weight"?"kg":"cm"})</th><td>{from?.[key]||"—"}</td><td>{to?.[key]||"—"}</td><td>{from?.[key]&&to?.[key]?(to[key]-from[key]).toFixed(1):"—"}</td></tr>)}</tbody></table></div></Card>}
    <div className="le-row my-6"><h2>Progress photos</h2><Button onClick={addPhoto}><Plus size={16}/>Add progress photo</Button></div>{!data.fitnessPhotos.length?<Empty title="A visual record, at your own pace." action="Add photo" onClick={addPhoto}/>:<div className="le-grid-three">{data.fitnessPhotos.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(p=><Card key={p.id}><MediaImage source={p.image} alt={p.title}/><p className="le-eyebrow mt-4">{p.date}</p><h3>{p.title}</h3><p className="le-muted">{p.notes}</p><RecordActions name={p.title} edit={()=>setPhoto(p)} remove={()=>update(d=>({...d,fitnessPhotos:d.fitnessPhotos.filter(x=>x.id!==p.id)}))}/></Card>)}</div>}
    {photo&&<Modal title="Progress photo" close={()=>setPhoto(null)}><form onSubmit={e=>{e.preventDefault();if(!photo.image||uploading)return;update(d=>({...d,fitnessPhotos:[...d.fitnessPhotos.filter(p=>p.id!==photo.id),photo]}));setPhoto(null);}}><Field label="Photo title"><input required value={photo.title} onChange={e=>setPhoto({...photo,title:e.target.value})}/></Field><Field label="Photo date"><input type="date" required value={photo.date} onChange={e=>setPhoto({...photo,date:e.target.value})}/></Field><ImageUpload value={photo.image} onBusy={setUploading} onChange={image=>setPhoto(p=>p?{...p,image}:p)}/><Field label="Photo notes"><textarea value={photo.notes} onChange={e=>setPhoto({...photo,notes:e.target.value})}/></Field><Button type="submit" disabled={!photo.image||uploading}>Save photo</Button></form></Modal>}
  </>;
}
