"use client";
import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, CircleAlert, Plus, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { useLife,pillars,today,uid } from "@/lib/life-store";
import { budgetGuidanceSummary, journalRatingStats, nextReviewDate,reviewDue,type Review } from "@/lib/refinements";
import { pillarEvidence } from "@/lib/pillar-evidence";
import { Button,Card,Field,Heading,Modal,Progress,RecordActions,SaveButton } from "./workspace-ui";
import { Trend } from "./fitness-progress";
export function InsightsWorkspace() {
  const {data,update}=useLife();const [trendPillar,setTrendPillar]=useState(data.lifePillars?.[0]??pillars[0]);const [period,setPeriod]=useState("30");const [draft,setDraft]=useState<Review|null>(null);const date=today();const history=data.reviews.slice().sort((a,b)=>a.date.localeCompare(b.date));const latest=history.at(-1);const previous=history.at(-2)?.ratings??data.assessment;const current=latest?.ratings??data.assessment;
  const currentPillars=data.lifePillars?.length?data.lifePillars:pillars;const days=Number(period);const start=(()=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()-days+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;})();
  const recent=(value:string)=>value>=start&&value<=date;const due=reviewDue(data,date);const next=nextReviewDate(latest?.date??data.reviewSchedule.start,data.reviewSchedule.frequency);const finance=budgetGuidanceSummary(data,date,data.currency);const evidence=pillarEvidence(data,date);const selectedPillar=currentPillars.includes(trendPillar)?trendPillar:currentPillars[0]??"Personal Growth";
  const add=()=>setDraft({id:uid(),date,ratings:Object.fromEntries(currentPillars.map(p=>[p,current[p]??5])),notes:""});
  const summaries=currentPillars.map(p=>{
    const stats=journalRatingStats(data,p,date);const goals=data.goals.filter(g=>!g.archived&&g.pillars.includes(p));const doneTasks=data.tasks.filter(t=>t.pillar===p&&t.done&&recent(t.date)).length;const journals=data.journals.filter(j=>j.pillar===p&&recent(j.date)).length;const score=evidence.find(row=>row.pillar===p)?.score??0;
    let label="Not enough recent data";let tone:"up"|"down"|"steady"|"quiet"="quiet";
    if(p==="Financial"&&finance.monthlyBudget>0){label=finance.health;tone=finance.health.includes("Risk")||finance.health.includes("Above")?"down":"up";}
    else if(p==="Physical"&&data.workoutLogs.some(l=>recent(l.date))){const active=new Set(data.workoutLogs.filter(l=>recent(l.date)).map(l=>l.date)).size;label=`${active} active workout ${active===1?"day":"days"}`;tone=active>=3?"up":"steady";}
    else if((p==="Mental & Emotional"||p==="Personal Growth"||stats.rows.length)&&stats.rows.length>=2){label=`Self-assessments ${stats.trend.toLowerCase()}`;tone=stats.trend==="Improving"?"up":stats.trend==="Declining"?"down":"steady";}
    else if(p==="Social"&&data.relationships.some(r=>!r.archived&&((r.lastContact&&recent(r.lastContact))||r.followUp>=date))){const dueNow=data.relationships.filter(r=>!r.archived&&r.followUp&&r.followUp<=date).length;label=dueNow?`${dueNow} check-in${dueNow===1?"":"s"} due`:"Connections recently updated";tone=dueNow?"down":"up";}
    else if(p==="Spiritual"&&(data.prayers.some(pr=>!pr.archived&&recent(pr.date))||data.studyPlans.some(plan=>!plan.archived&&plan.progress>0))){label="Spiritual rhythm recorded";tone="up";}
    else if(goals.length){const avg=Math.round(goals.reduce((s,g)=>s+g.progress,0)/goals.length);label=`Goal progress averages ${avg}%`;tone=avg>=60?"up":avg>0?"steady":"quiet";}
    else if(doneTasks){label=`${doneTasks} completed action${doneTasks===1?"":"s"}`;tone="up";}
    else if(journals){label=`${journals} reflection${journals===1?"":"s"} written`;tone="steady";}
    return {pillar:p,label,tone,score,stats,goals,journals,doneTasks};
  });
  const changes=currentPillars.filter(p=>current[p]&&previous[p]).map(p=>({pillar:p,change:current[p]-previous[p]})).sort((a,b)=>b.change-a.change);
  const positives=summaries.filter(s=>s.tone==="up").slice(0,2);const attention=summaries.filter(s=>s.tone==="down"||s.label==="Not enough recent data").slice(0,2);
  const focusMinutes=Math.round(data.focus.filter(f=>recent(f.date)).reduce((s,f)=>s+f.seconds,0)/60);const completedGoals=data.goals.filter(g=>!g.archived&&g.progress===100).length;const activeDays=new Set([...data.tasks.filter(t=>t.done&&recent(t.date)).map(t=>t.date),...data.workoutLogs.filter(l=>recent(l.date)).map(l=>l.date),...data.journals.filter(j=>recent(j.date)).map(j=>j.date)]).size;
  const observations=[
    finance.monthlyBudget>0&&finance.health.includes("Risk")?`Financial spending is above plan for the current pay cycle.`:"",
    data.workoutLogs.filter(l=>recent(l.date)).length>=3?`Workout consistency is visible in the selected period.`:"",
    focusMinutes>0?`${focusMinutes} focused minutes were recorded in this period.`:"",
    changes[0]?.change>0?`${changes[0].pillar} improved in your latest life balance review.`:"",
    summaries.find(s=>s.stats.trend==="Improving")?`${summaries.find(s=>s.stats.trend==="Improving")?.pillar} journal ratings are trending upward.`:""
  ].filter(Boolean).slice(0,4);
  return <><Heading section="Insights" title="Your life at a glance."><div className="le-inline"><Field label="Period"><select value={period} onChange={e=>setPeriod(e.target.value)}>{["7","30","90"].map(value=><option key={value} value={value}>{value} days</option>)}</select></Field><Button onClick={add}><Plus size={16}/>Life balance review</Button></div></Heading>{due&&<div className="le-welcome"><h2>Life balance review is due.</h2><Button onClick={add}>Review now</Button></div>}
    <section className="le-insights-hero"><div><p className="le-eyebrow">Your Life at a Glance</p><h2>{positives[0]?`${positives[0].pillar} is showing positive movement.`:activeDays?`${activeDays} active ${activeDays===1?"day":"days"} recorded.`:"Start with one recorded action."}</h2><p>{attention[0]?`${attention[0].pillar}: ${attention[0].label}.`:"No urgent attention pattern is standing out from recorded data."}</p></div><div className="le-insights-pulse"><div><Sparkles size={18}/><strong>{activeDays}</strong><span>active days</span></div><div><CheckCircle2 size={18}/><strong>{completedGoals}</strong><span>completed goals</span></div><div><CalendarDays size={18}/><strong>{history.length}</strong><span>reviews</span></div></div></section>
    <div className="le-grid-three mt-6">{summaries.map(summary=>{const Icon=summary.tone==="up"?TrendingUp:summary.tone==="down"?TrendingDown:summary.tone==="steady"?ArrowRight:CircleAlert;return <button type="button" key={summary.pillar} className={`le-pillar-insight is-${summary.tone}`} aria-pressed={selectedPillar===summary.pillar} onClick={()=>setTrendPillar(summary.pillar)}><div><p>{summary.pillar}</p><h3>{summary.label}</h3></div><Icon size={20}/><Progress value={summary.score}/></button>;})}</div>
    <div className="le-grid-two mt-6"><Trend title={`${selectedPillar} over time`} points={journalRatingStats(data,selectedPillar,date).rows.slice(-18).map(r=>({date:r.date,value:r.rating}))} unit="/ 10"/><Card className="le-insight-detail"><div className="le-row"><div><p className="le-eyebrow">{selectedPillar}</p><h2>What is shaping this pillar</h2></div><span className="le-chip">{journalRatingStats(data,selectedPillar,date).trend}</span></div>{(evidence.find(p=>p.pillar===selectedPillar)?.items??[]).map(item=><p key={item.action} className="le-log">{item.met?item.action:item.missing}</p>)}{!(evidence.find(p=>p.pillar===selectedPillar)?.items.length)&&<p className="le-muted">More activity is needed before this pillar can show a reliable pattern.</p>}</Card></div>
    <div className="le-grid-two mt-6"><Card><div className="le-row"><h2>Worth noticing</h2><span className="le-chip">{period} days</span></div>{observations.length?observations.map(item=><p className="le-log" key={item}>{item}</p>):<p className="le-muted mt-4">No clear pattern yet. Add reflections, plans, workouts, goals, or finance activity and this view will sharpen.</p>}</Card><Card><div className="le-row"><h2>Review rhythm</h2><Button secondary onClick={add}>Add review</Button></div><Field label="Review frequency"><select value={data.reviewSchedule.frequency} onChange={e=>update(d=>({...d,reviewSchedule:{...d.reviewSchedule,frequency:e.target.value as typeof d.reviewSchedule.frequency}}))}>{["Weekly","Monthly","Quarterly"].map(f=><option key={f}>{f}</option>)}</select></Field><label className="le-check-row"><input type="checkbox" checked={data.reviewSchedule.enabled} onChange={e=>update(d=>({...d,reviewSchedule:{...d.reviewSchedule,enabled:e.target.checked,start:d.reviewSchedule.start||today()}}))}/>Remind me in the app</label><p className="le-muted mt-4">{data.reviewSchedule.enabled?due?"Due now":`Next review: ${next}`:"Paused"}</p></Card></div>
    {history.length>0&&<><div className="le-row my-6"><h2>Recent reviews</h2><Button secondary onClick={add}>Add review</Button></div>{history.slice(-3).reverse().map(r=><Card key={r.id} className="mb-5"><div className="le-row"><h3>{r.date}</h3><RecordActions name={`review ${r.date}`} edit={()=>setDraft(r)} remove={()=>update(d=>({...d,reviews:d.reviews.filter(x=>x.id!==r.id)}))}/></div><dl className="le-record-details">{currentPillars.map(p=><div key={p}><dt>{p}</dt><dd>{r.ratings[p]??"—"} / 10</dd></div>)}</dl>{r.notes&&<p className="le-muted mt-4">{r.notes}</p>}</Card>)}</>}
    {draft&&<Modal title="Life balance review" close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,reviews:[...d.reviews.filter(r=>r.id!==draft.id),draft]}));setDraft(null);}}><Field label="Review date"><input type="date" max={today()} required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></Field>{currentPillars.map(p=><Field key={p} label={`${p} rating`}><input type="number" min="1" max="10" step="1" required value={draft.ratings[p]} onChange={e=>setDraft({...draft,ratings:{...draft.ratings,[p]:Number(e.target.value)}})}/></Field>)}<Field label="Review notes"><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><SaveButton>Save review</SaveButton></form></Modal>}
  </>;
}
