"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLife,pillars,today,uid } from "@/lib/life-store";
import { nextReviewDate,reviewDue,type Review } from "@/lib/refinements";
import { pillarEvidence } from "@/lib/pillar-evidence";
import { Button,Card,Field,Heading,Metric,Modal,Progress,RecordActions } from "./workspace-ui";
import { Trend } from "./fitness-progress";
export function InsightsWorkspace() {
  const {data,update}=useLife();const [trendPillar,setTrendPillar]=useState("Overall");const [draft,setDraft]=useState<Review|null>(null);const history=data.reviews.slice().sort((a,b)=>a.date.localeCompare(b.date));const latest=history.at(-1);const previous=history.at(-2)?.ratings??data.assessment;const current=latest?.ratings??data.assessment;
  const changes=pillars.filter(p=>current[p]&&previous[p]).map(p=>({pillar:p,change:current[p]-previous[p]})).sort((a,b)=>b.change-a.change);const attention=pillars.filter(p=>current[p]).sort((a,b)=>current[a]-current[b])[0];const due=reviewDue(data,today());const next=nextReviewDate(latest?.date??data.reviewSchedule.start,data.reviewSchedule.frequency);
  const add=()=>setDraft({id:uid(),date:today(),ratings:Object.fromEntries(pillars.map(p=>[p,current[p]??5])),notes:""});
  return <><Heading section="Notice the bigger picture" title="Understand your life balance."><Button onClick={add}><Plus size={16}/>Life balance review</Button></Heading>{due&&<div className="le-welcome"><h2>Would you like to update your Life Balance Assessment?</h2><Button onClick={add}>Review now</Button></div>}<div className="le-grid-three"><Metric label="Largest improvement" value={changes[0]?.change>0?`${changes[0].pillar} +${changes[0].change}`:changes.length?"No increase recorded":"More reviews needed"}/><Metric label="Area needing attention" value={attention??"Start with an assessment"}/><Metric label="Reviews completed" value={history.length}/></div><div className="le-grid-two mt-6"><div><Field label="Review trend pillar"><select value={trendPillar} onChange={e=>setTrendPillar(e.target.value)}>{["Overall",...pillars].map(p=><option key={p}>{p}</option>)}</select></Field><Trend title={trendPillar==="Overall"?"Self-assessment growth":`${trendPillar} growth`} points={history.map(r=>({date:r.date,value:trendPillar==="Overall"?Number((pillars.reduce((s,p)=>s+(r.ratings[p]??0),0)/6).toFixed(1)):r.ratings[trendPillar]}))} unit="/ 10"/></div><Card><h2>Your review rhythm</h2><Field label="Review frequency"><select value={data.reviewSchedule.frequency} onChange={e=>update(d=>({...d,reviewSchedule:{...d.reviewSchedule,frequency:e.target.value as typeof d.reviewSchedule.frequency}}))}>{["Weekly","Monthly","Quarterly"].map(f=><option key={f}>{f}</option>)}</select></Field><label className="le-check-row"><input type="checkbox" checked={data.reviewSchedule.enabled} onChange={e=>update(d=>({...d,reviewSchedule:{...d.reviewSchedule,enabled:e.target.checked,start:d.reviewSchedule.start||today()}}))}/>Remind me in the app</label><p className="le-muted mt-4">{data.reviewSchedule.enabled?due?"Your review is due.":`Next review: ${next}`:"Review prompts are paused."}</p></Card></div>
    <div className="my-8"><h2>What contributes to your pillars</h2><p className="le-muted mt-3">Self-ratings are your assessment out of 10. Action alignment measures three equally weighted signals per pillar. Activity uses the last 30 days, finances use this month, and goals and study plans use their current status. Missing records are not a judgment of your wellbeing.</p></div><div className="le-grid-two">{pillarEvidence(data,today()).map(p=><Card key={p.pillar}><div className="le-row"><h2>{p.pillar}</h2><span className="le-chip">Self-rating: {current[p.pillar]??"—"} / 10</span></div><div className="le-row mt-4"><span>Action alignment</span><strong>{p.score}%</strong></div><Progress value={p.score}/><h3 className="mt-5">What supports it</h3>{p.items.filter(i=>i.met).length?p.items.filter(i=>i.met).map(i=><p className="le-muted mt-2" key={i.action}>✓ {i.action}</p>):<p className="le-muted mt-3">No contributing actions recorded yet.</p>}<h3 className="mt-5">What holds it back</h3>{p.items.filter(i=>!i.met).length?p.items.filter(i=>!i.met).map(i=><p className="le-muted mt-2" key={i.action}>{i.missing}</p>):<p className="le-muted mt-3">All three signals are present.</p>}<p className="mt-5"><strong>Next action: </strong>{p.items.find(i=>!i.met)?.next??"Keep your current rhythm."}</p></Card>)}</div>
    <div className="le-row my-6"><h2>Review history</h2><Button secondary onClick={add}>Add review</Button></div>{history.map(r=><Card key={r.id} className="mb-5"><div className="le-row"><h3>{r.date}</h3><RecordActions name={`review ${r.date}`} edit={()=>setDraft(r)} remove={()=>update(d=>({...d,reviews:d.reviews.filter(x=>x.id!==r.id)}))}/></div><dl className="le-record-details">{pillars.map(p=><div key={p}><dt>{p}</dt><dd>{r.ratings[p]} / 10</dd></div>)}</dl><p className="le-muted mt-4">{r.notes}</p></Card>)}
    {draft&&<Modal title="Life balance review" close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,reviews:[...d.reviews.filter(r=>r.id!==draft.id),draft]}));setDraft(null);}}><Field label="Review date"><input type="date" max={today()} required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></Field>{pillars.map(p=><Field key={p} label={`${p} rating`}><input type="number" min="1" max="10" step="1" required value={draft.ratings[p]} onChange={e=>setDraft({...draft,ratings:{...draft.ratings,[p]:Number(e.target.value)}})}/></Field>)}<Field label="Review notes"><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><Button type="submit">Save review</Button></form></Modal>}
  </>;
}
