"use client";
import { useEffect, useRef, useState } from "react";
import { Plus } from "lucide-react";
import { useLife, uid, today, type LifeData } from "@/lib/life-store";
import { Button, Card, Empty, Field, Heading, Modal, RecordActions, Tabs } from "./workspace-ui";

type RecordValue = string | number | boolean | string[];
type Managed = { id: string; [key: string]: RecordValue };
type Collection = "relationships" | "prayers" | "studyPlans" | "savingsGoals" | "templates" | "measurements";
export type RecordField = { key: string; label: string; type?: "text" | "date" | "number" | "textarea" | "checkbox" | "select" | "lines"; options?: string[]; min?: number; max?: number; required?: boolean; initial?: RecordValue };
export function RecordManager({ collection, title, singular, fields, archive = true, createRequest = 0 }: { collection: Collection; title: string; singular: string; fields: RecordField[]; archive?: boolean; createRequest?: number }) {
  const { data, update } = useLife(); const rows = data[collection] as unknown as Managed[]; const [draft, setDraft] = useState<Managed | null>(null); const [archived, setArchived] = useState(false);
  const add = () => setDraft({ id: uid(), ...(archive ? { archived: false } : {}), ...Object.fromEntries(fields.map(f => [f.key, f.initial ?? (f.type === "number" ? 0 : f.type === "checkbox" ? false : f.type === "lines" ? [] : f.type === "select" ? f.options?.[0] ?? "" : "")])) });
  const handledRequest = useRef(0);
  useEffect(() => {
    if (createRequest <= handledRequest.current) return;
    handledRequest.current = createRequest;
    setDraft({ id: uid(), ...(archive ? { archived: false } : {}), ...Object.fromEntries(fields.map(f => [f.key, f.initial ?? (f.type === "number" ? 0 : f.type === "checkbox" ? false : f.type === "lines" ? [] : f.type === "select" ? f.options?.[0] ?? "" : "")])) });
  }, [createRequest, archive, fields]);
  const mutate = (fn: (rows: Managed[]) => Managed[]) => update(d => ({ ...d, [collection]: fn(d[collection] as unknown as Managed[]) }));
  return <section><div className="le-row my-5"><h2>{title}</h2><div className="le-inline">{archive && <label className="le-inline"><input type="checkbox" checked={archived} onChange={e => setArchived(e.target.checked)} />Show archived</label>}<Button onClick={add}><Plus size={16} />Add {singular}</Button></div></div>{!rows.filter(r => !archive || Boolean(r.archived) === archived).length ? <Empty title={`No ${title.toLowerCase()} yet.`} action={`Create ${singular}`} onClick={add} /> : <div className="le-grid-two">{rows.filter(r => !archive || Boolean(r.archived) === archived).map(row => <Card key={row.id}><div className="le-row"><h3>{String(row.title ?? row.name ?? row.date)}</h3><RecordActions name={String(row.title ?? row.name ?? row.date)} edit={() => setDraft({ ...Object.fromEntries(fields.map(f => [f.key, f.initial ?? (f.type === "number" ? 0 : f.type === "checkbox" ? false : f.type === "select" ? f.options?.[0] ?? "" : f.type === "lines" ? [] : "")])), ...row })} remove={() => mutate(items => items.filter(x => x.id !== row.id))} archived={Boolean(row.archived)} archive={archive ? () => mutate(items => items.map(x => x.id === row.id ? { ...x, archived: !x.archived } : x)) : undefined} /></div><dl className="le-record-details">{fields.filter(f => f.key !== "name" && f.key !== "title").map(f => <div key={f.key}><dt>{f.label}</dt><dd>{Array.isArray(row[f.key]) ? (row[f.key] as string[]).join(" · ") : typeof row[f.key] === "boolean" ? row[f.key] ? "Yes" : "No" : String(row[f.key] === "" || row[f.key] === undefined ? "—" : row[f.key])}</dd></div>)}</dl>{collection === "savingsGoals" && <p className="le-chip mt-4">{Number(row.target) > 0 ? Math.round(Number(row.saved) / Number(row.target) * 100) : 0}% saved</p>}</Card>)}</div>}
    {draft && <Modal title={`${rows.some(r => r.id === draft.id) ? "Edit" : "Create"} ${singular}`} close={() => setDraft(null)}><form onSubmit={e => { e.preventDefault(); mutate(items => [...items.filter(x => x.id !== draft.id), draft]); setDraft(null); }}>{fields.map(f => <Field label={f.label} key={f.key}>{f.type === "select" ? <select value={String(draft[f.key])} onChange={e => setDraft({ ...draft, [f.key]: e.target.value })}>{[...new Set([...(f.options ?? []), String(draft[f.key])])].filter(Boolean).map(v => <option key={v}>{v}</option>)}</select> : f.type === "textarea" || f.type === "lines" ? <textarea required={f.required} rows={4} value={Array.isArray(draft[f.key]) ? (draft[f.key] as string[]).join("\n") : String(draft[f.key])} onChange={e => setDraft({ ...draft, [f.key]: f.type === "lines" ? e.target.value.split("\n") : e.target.value })} /> : f.type === "checkbox" ? <input type="checkbox" checked={Boolean(draft[f.key])} onChange={e => setDraft({ ...draft, [f.key]: e.target.checked })} /> : <input required={f.required} type={f.type ?? "text"} min={f.min} max={f.max} step={f.type === "number" ? "any" : undefined} value={String(draft[f.key] ?? "")} onChange={e => setDraft({ ...draft, [f.key]: f.type === "number" ? Number(e.target.value) : e.target.value })} />}</Field>)}<Button type="submit" className="le-compact-save">Save {singular}</Button></form></Modal>}
  </section>;
}
type CategoryKey = "categories" | "workoutTypes" | "exerciseCategories" | "areas" | "focusTypes" | "visionCategories" | "relationshipTypes";
export function CategoryManager({ categoryKey, title }: { categoryKey: CategoryKey; title: string }) {
  const { data, update, offerUndo } = useLife(); const [edit, setEdit] = useState<{ old: string; name: string } | null>(null); const [error, setError] = useState("");
  function rename(d: LifeData, old: string, name: string): LifeData {
    const next = { ...d, [categoryKey]: d[categoryKey].map(v => v === old ? name : v) };
    if (categoryKey === "categories") { next.transactions = d.transactions.map(t => t.category === old ? { ...t, category: name } : t); next.budgets = d.budgets.map(b => b.category === old ? { ...b, category: name } : b); }
    if (categoryKey === "workoutTypes") next.workouts = d.workouts.map(w => w.category === old ? { ...w, category: name } : w);
    if (categoryKey === "exerciseCategories") next.exercises = d.exercises.map(ex => ex.category === old ? { ...ex, category: name } : ex);
    if (categoryKey === "areas") { next.priorities = d.priorities.map(p => p === old ? name : p); next.tasks = d.tasks.map(t => t.pillar === old ? { ...t, pillar: name } : t); }
    if (categoryKey === "visionCategories") next.board = d.board.map(b => b.category === old ? { ...b, category: name } : b);
    if (categoryKey === "relationshipTypes") next.relationships = d.relationships.map(r => r.type === old ? { ...r, type: name } : r);
    return next;
  }
  return <Card className="le-category-card"><div className="le-row"><div><p className="le-eyebrow">Library</p><h2>{title}</h2></div><Button secondary onClick={() => { setEdit({ old: "", name: "" }); setError(""); }}><Plus size={16} />Add category</Button></div><div className="le-category-list">{data[categoryKey].map(name => <div className="le-row" key={name}><span>{name}</span><RecordActions name={name} edit={() => { setEdit({ old: name, name }); setError(""); }} remove={() => { update(d => ({ ...d, [categoryKey]: d[categoryKey].filter(v => v !== name) })); offerUndo(`Deleted ${name}. Existing records are preserved.`, d => ({ ...d, [categoryKey]: [...new Set([...d[categoryKey], name])] })); }} /></div>)}</div>{edit && <Modal title="Category" close={() => setEdit(null)}><form onSubmit={e => { e.preventDefault(); const name = edit.name.trim(); if (!name || data[categoryKey].some(v => v.toLowerCase() === name.toLowerCase() && v !== edit.old)) { setError("Choose a unique category name."); return; } update(d => edit.old ? rename(d, edit.old, name) : { ...d, [categoryKey]: [...d[categoryKey], name] }); setEdit(null); }}><Field label="Category name"><input required value={edit.name} onChange={e => setEdit({ ...edit, name: e.target.value })} /></Field>{error && <p role="alert">{error}</p>}<Button type="submit">Save category</Button></form></Modal>}</Card>;
}
export function SocialWorkspace() { return <><Heading section="People who matter" title="Connection, with intention." /><RecordManager collection="relationships" title="Relationships" singular="relationship" fields={[{ key:"name",label:"Name",required:true },{ key:"birthday",label:"Birthday",type:"date" },{ key:"followUp",label:"Next follow-up",type:"date" },{ key:"goal",label:"Connection goal" },{ key:"notes",label:"Notes",type:"textarea" }]} /></>; }
export function SpiritualWorkspace() { const [tab,setTab]=useState("Prayer requests"); return <><Heading section="Faith and reflection" title="A space for what grounds you." /><Tabs items={["Prayer requests","Bible study plans"]} active={tab} onChange={setTab} />{tab === "Prayer requests" ? <RecordManager collection="prayers" title="Prayer requests" singular="prayer request" fields={[{ key:"title",label:"Title",required:true },{ key:"date",label:"Date",type:"date",initial:today(),required:true },{ key:"notes",label:"Prayer and reflection",type:"textarea" },{ key:"answered",label:"Answered",type:"checkbox" }]} /> : <RecordManager collection="studyPlans" title="Bible study plans" singular="Bible study plan" fields={[{ key:"title",label:"Title",required:true },{ key:"passage",label:"Passage or reading plan",required:true },{ key:"date",label:"Target date",type:"date" },{ key:"progress",label:"Progress (%)",type:"number",min:0,max:100 },{ key:"notes",label:"Study notes",type:"textarea" }]} />}</>; }
