"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLife,uid,type LifeData } from "@/lib/life-store";
import { Button,Card,Empty,Field,Modal,RecordActions } from "./workspace-ui";
import { CategoryManager } from "./record-manager";
import { ImageUpload,MediaImage } from "./workspace-media";
export function VisionWorkspace() {
  const {data,update}=useLife();const [draft,setDraft]=useState<LifeData["board"][number]|null>(null);const [category,setCategory]=useState("All");const [settings,setSettings]=useState(false);const [uploading,setUploading]=useState(false);
  const add=()=>setDraft({id:uid(),title:"",url:"",notes:"",category:data.visionCategories[0]??"Other",goalId:""});
  return <><div className="le-row my-6"><h2>Keep your future in view.</h2><div className="le-inline"><select aria-label="Vision category filter" value={category} onChange={e=>setCategory(e.target.value)}>{["All",...new Set([...data.visionCategories,...data.board.map(b=>b.category??"Other")])].map(c=><option key={c}>{c}</option>)}</select><Button secondary onClick={()=>setSettings(!settings)}>Categories</Button><Button onClick={add}><Plus size={16}/>Add vision item</Button></div></div>{settings&&<CategoryManager categoryKey="visionCategories" title="Vision categories"/>}{!data.board.length?<Empty title="What does your next chapter look like?" action="Create vision item" onClick={add}/>:<div className="le-grid-three mt-5">{data.board.filter(b=>category==="All"||(b.category??"Other")===category).map(b=><Card key={b.id}>{b.url&&<MediaImage source={b.url} alt={b.title}/>}<p className="le-eyebrow mt-5">{b.category??"Other"}</p><h3>{b.title}</h3><p className="le-muted my-4">{b.notes}</p>{b.goalId&&<p className="le-chip">Goal: {data.goals.find(g=>g.id===b.goalId)?.title??"Removed goal"}</p>}<RecordActions name={b.title} edit={()=>setDraft(b)} remove={()=>update(d=>({...d,board:d.board.filter(x=>x.id!==b.id)}))}/></Card>)}</div>}{draft&&<Modal title="Vision item" close={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();update(d=>({...d,board:[...d.board.filter(b=>b.id!==draft.id),draft]}));setDraft(null);}}><Field label="Title"><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="Category"><select value={draft.category??"Other"} onChange={e=>setDraft({...draft,category:e.target.value})}>{[...new Set([...data.visionCategories,draft.category??"Other"])].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Motivation notes"><textarea rows={4} value={draft.notes??""} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><Field label="Future goal"><select value={draft.goalId??""} onChange={e=>setDraft({...draft,goalId:e.target.value})}><option value="">No linked goal</option>{data.goals.filter(g=>!g.archived||g.id===draft.goalId).map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></Field><ImageUpload value={draft.url} onBusy={setUploading} onChange={url=>setDraft(d=>d?{...d,url}:d)}/><Field label="Or image URL (https)"><input type="url" pattern="https://.*" value={draft.url.startsWith("https://")?draft.url:""} onChange={e=>setDraft({...draft,url:e.target.value})}/></Field>{draft.url&&<Button secondary onClick={()=>setDraft({...draft,url:""})}>Remove image</Button>}<Button type="submit" disabled={uploading}>Save vision item</Button></form></Modal>}</>;
}
