"use client";
import { Children, cloneElement, isValidElement, useEffect, useId, useRef, type ReactElement, type ReactNode } from "react";
import { Archive, Pencil, Plus, Trash2, X } from "lucide-react";

export function Button({ children, onClick, type = "button", secondary = false, disabled = false }: { children: ReactNode; onClick?: () => void; type?: "button" | "submit"; secondary?: boolean; disabled?: boolean }) { return <button type={type} disabled={disabled} onClick={onClick} className={`le-button ${secondary ? "le-secondary" : ""}`}>{children}</button>; }
export function IconButton({ title, children, onClick }: { title: string; children: ReactNode; onClick: () => void }) { return <button type="button" className="le-icon" title={title} aria-label={title} onClick={onClick}>{children}</button>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`le-card ${className}`}>{children}</section>; }
export function Heading({ section, title, children }: { section: string; title: string; children?: ReactNode }) { return <div className="le-heading"><div><p className="le-eyebrow">{section}</p><h1>{title}</h1></div>{children}</div>; }
export function Field({ label, children }: { label: string; children: ReactNode }) { const id = useId(); return <div className="le-field"><label htmlFor={id}>{label}</label>{Children.map(children, child => isValidElement(child) && typeof child.type === "string" && ["input", "textarea", "select"].includes(child.type) ? cloneElement(child as ReactElement<{ id: string }>, { id }) : child)}</div>; }
export function Empty({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="le-empty">{onClick ? <button type="button" className="le-empty-mark" aria-label={action ?? title} onClick={onClick}><Plus size={22} /></button> : <div className="le-empty-mark" aria-hidden="true"><Plus size={22} /></div>}<h3>{title}</h3>{action && <Button onClick={onClick}><Plus size={16} />{action}</Button>}</div>; }
export function Tabs({ items, active, onChange }: { items: string[]; active: string; onChange: (v: string) => void }) { return <div className="le-tabs" role="tablist">{items.map(item => <button type="button" role="tab" aria-selected={active === item} key={item} onClick={() => onChange(item)}>{item}</button>)}</div>; }
export function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []); return <dialog ref={ref} className="le-modal" aria-label={title} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="le-row"><h2>{title}</h2><IconButton title="Close dialog" onClick={close}><X size={20} /></IconButton></div>{children}</dialog>; }
export function Progress({ value }: { value: number }) { return <div className="le-progress" role="progressbar" aria-valuenow={Math.min(100, value)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
export function RecordActions({ name, edit, remove, archive, archived }: { name: string; edit: () => void; remove: () => void; archive?: () => void; archived?: boolean }) { return <div className="le-inline"><IconButton title={`Edit ${name}`} onClick={edit}><Pencil size={16} /></IconButton>{archive && <IconButton title={`${archived ? "Restore" : "Archive"} ${name}`} onClick={archive}><Archive size={16} /></IconButton>}<IconButton title={`Delete ${name}`} onClick={remove}><Trash2 size={16} /></IconButton></div>; }
export function Metric({ label, value, color }: { label: string; value: ReactNode; color?: string }) { return <Card><p className="le-eyebrow">{label}</p><p className="le-metric" style={{ color }}>{value}</p></Card>; }
