import type { LifeData } from "./life-store";
import { financialTotals, paydayCycleForDate } from "./refinements";
export function pillarEvidence(data:LifeData,date:string) {
  const since=new Date(`${date}T12:00:00`);since.setDate(since.getDate()-29);const cutoff=`${since.getFullYear()}-${String(since.getMonth()+1).padStart(2,"0")}-${String(since.getDate()).padStart(2,"0")}`;
  const recent=(d:string)=>d>=cutoff&&d<=date;
  const cycle=paydayCycleForDate(date,data.financeSettings?.payday);const transactions=data.transactions.filter(t=>t.currency===data.currency&&t.date>=cycle.start&&t.date<=date);const budgets=data.budgets.filter(b=>b.currency===data.currency&&b.month===cycle.budgetMonth);
  const goals=(pillar:string)=>data.goals.some(g=>!g.archived&&g.progress===100&&g.pillars.includes(pillar));
  const mental=data.journals.filter(j=>j.pillar==="Mental & Emotional"&&recent(j.date));
  type Signal={met:boolean;action:string;missing:string;next:string};
  const signal=(met:boolean,action:string,missing:string,next:string):Signal=>({met,action,missing,next});
  const signals:Record<string,Signal[]>={
    Financial:[signal(transactions.length>0,"Updated spending tracker","No transactions recorded this pay cycle","Record your recent transactions."),signal(financialTotals(transactions).savings>0,"Added savings","No savings recorded this pay cycle","Record a savings contribution when you make one."),signal(budgets.length>0&&transactions.some(t=>t.type!=="Income")&&budgets.every(b=>transactions.filter(t=>t.type!=="Income"&&t.category===b.category).reduce((s,t)=>s+t.amount,0)<=b.amount),"Stayed within tracked category budgets","A category is over budget, or budget evidence is incomplete","Review your category budgets and actual spending.")],
    Physical:[signal(data.workoutLogs.some(l=>recent(l.date)),"Logged workouts","No workout logged in the last 30 days","Log your next workout."),signal(data.measurements.some(m=>recent(m.date)),"Updated body measurements","No progress entry in the last 30 days","Add a progress entry when useful to you."),signal(goals("Physical"),"Completed a fitness goal","No completed physical goal recorded","Choose one achievable physical goal.")],
    "Mental & Emotional":[signal(mental.length>0,"Journaled about mental wellbeing","No mental reflection in the last 30 days","Write a mental and emotional reflection."),signal(new Set(mental.map(j=>j.date)).size>=3,"Reflected on at least three days","Fewer than three reflection days this month","Make a little time for another reflection."),signal(data.tasks.some(t=>t.done&&t.pillar==="Mental & Emotional"&&recent(t.date)),"Completed a mental wellbeing action","No mental wellbeing action completed recently","Plan a small activity that supports your wellbeing.")],
    Social:[signal(data.relationships.some(r=>!r.archived&&r.lastContact&&recent(r.lastContact)),"Connected with someone recently","No recent contact date recorded","Reach out to someone important to you."),signal(data.relationships.some(r=>!r.archived&&r.followUp>=date),"Planned a future check-in","No upcoming check-in set","Choose your next check-in date."),signal(goals("Social"),"Completed a connection goal","No completed social goal recorded","Review your relationship goals.")],
    Spiritual:[signal(data.prayers.some(p=>!p.archived&&recent(p.date)),"Recorded a prayer","No recent prayer recorded","Add a prayer or reflection."),signal(data.studyPlans.some(p=>!p.archived&&p.progress>0),"Progressed a study plan","No study progress recorded","Update a reading or study plan."),signal(data.journals.some(j=>j.pillar==="Spiritual"&&recent(j.date)),"Wrote a spiritual reflection","No recent spiritual reflection","Reflect on your spiritual practice.")],
    "Personal Growth":[signal(data.focus.some(f=>recent(f.date)),"Completed focused work","No recent focus session completed","Make time for one focused session."),signal(data.habits.some(h=>h.direction==="build"&&h.dates.some(recent)),"Kept a daily habit","No recent habit completion recorded","Keep one small daily promise."),signal(goals("Personal Growth"),"Completed a growth goal","No completed personal growth goal recorded","Review the next step toward your growth goal.")]
  };
  return Object.entries(signals).map(([pillar,items])=>({pillar,score:Math.round(items.filter(s=>s.met).length/items.length*100),items}));
}
